// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/leading-website/leading-website.component.ts
import { Component, input } from '@angular/core';

import { FormFieldComponent, InputComponent, LabelComponent, LeadingComponent } from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/leading-website.config';

@Component({
  selector: 'cck-leading-website',
  imports: [FormFieldComponent, InputComponent, LeadingComponent, LabelComponent],
  template: `
    <cck-form-field>
      <cck-label>Website URL</cck-label>
      <cck-leading>https://</cck-leading>
      <input cck-input />
    </cck-form-field>
  `,
  styles: ``,
})
export class LeadingWebsiteComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}

// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/leading-website/LeadingWebsite.tsx
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/leading-website.config';
import { FormField, Input, Label, Leading } from '@cocokits/react-components';

export function LeadingWebsite(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <FormField>
      <Label>Website URL</Label>
      <Leading>https://</Leading>
      <Input />
    </FormField>
  );
}
