// apps/angular-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-label-through/checkbox-label-through.component.ts
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-checkbox';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-label-through.config';

@Component({
  standalone: true,
  selector: 'cck-checkbox-label-through',
  imports: [CheckboxComponent],
  template: ` <cck-checkbox size="md" value="YOUR_VALUE" class="StrikedLabel"> Checkbox Label </cck-checkbox> `,
  styles: `
    .StrikedLabel {
      text-decoration: line-through;
      color: white;
    }
  `,
})
export class CheckboxLabelThroughComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}

// apps/react-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-label-through/CheckboxLabelThrough.tsx
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-label-through.config';
import { Checkbox } from '@cocokits/react-checkbox';

import { Styled } from './CheckboxLabelThrough.styled';

export function CheckboxLabelThrough(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <Checkbox size="md" value="YOUR_VALUE">
      <Styled.StrikedLabel>Checkbox Label</Styled.StrikedLabel>
    </Checkbox>
  );
}
