// packages/react/avatar/src/lib/avatar-group/avatar-group.tsx
import React from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';

export type AvatarGroupContextValue = UIBaseComponentProps;
export const AvatarGroupContext = React.createContext<AvatarGroupContextValue | null>(null);

export interface AvatarGroupProps extends UIBaseComponentProps {
  direction?: 'right' | 'left';
  children?: React.ReactNode;
}

export const AvatarGroup = ({ type, size, color, additional, children, direction = 'right' }: AvatarGroupProps) => {
  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'avatarGroup',
    props: { type, size, color, additional },
    extraHostElementClassConditions: [
      { if: direction === 'left', classes: (cn) => [cn.leftDirection] },
      { if: direction === 'right', classes: (cn) => [cn.rightDirection] },
    ],
  });

  return (
    <AvatarGroupContext.Provider value={{ type, size, color, additional }}>
      <div className={hostClassNames}>{children}</div>
    </AvatarGroupContext.Provider>
  );
};

AvatarGroup.displayName = 'AvatarGroup';
export default AvatarGroup;

// packages/angular/avatar/src/lib/avatar-group/avatar-group.component.ts
import { ChangeDetectionStrategy, Component, computed, input, ViewEncapsulation } from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';

@Component({
  imports: [],
  selector: 'cck-avatar-group',
  templateUrl: './avatar-group.component.html',
  styleUrls: ['./avatar-group.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
  },
})
export class AvatarGroupComponent extends _UiBaseComponent<'avatarGroup'> {
  protected readonly componentName = 'avatarGroup';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.direction() === 'left', classes: this.classNames().leftDirection },
    { if: this.direction() === 'right', classes: this.classNames().rightDirection },
  ]);

  public direction = input<'right' | 'left'>('right');
}

<p>cck-avatar-group works !!</p>
