// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/email-validation/email-validation.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';

import {
  ErrorComponent,
  FormFieldComponent,
  InputComponent,
  LabelComponent,
  SvgIconComponent,
} from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/email-validation.config';

@Component({
  selector: 'cck-email-validation',
  imports: [FormFieldComponent, LabelComponent, InputComponent, ErrorComponent, ReactiveFormsModule, SvgIconComponent],
  template: `
    <cck-form-field>
      <cck-label>Email</cck-label>
      <input cck-input [formControl]="emailControl" type="email" />

      <cck-error>
        <cck-svg-icon [icon]="Icons.warning"></cck-svg-icon>
        <span>Enter a valid email address</span>
      </cck-error>
    </cck-form-field>
  `,
  styles: ``,
})
export class EmailValidationComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  protected readonly Icons = Icons;
  protected emailControl = new FormControl('', [Validators.email, Validators.required]);
}

// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/email-validation/EmailValidation.tsx
import { useForm } from 'react-hook-form';

import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/email-validation.config';
import { Error, FormField, Input, Label, SvgIcon } from '@cocokits/react-components';

export function EmailValidation(props: { cckExampleArgs: ExampleArgs }) {
  const {
    control,
    formState: { errors },
  } = useForm<{ email: string }>({ mode: 'onTouched' });

  return (
    <FormField>
      <Label>Email</Label>
      <Input
        type="email"
        name="email"
        control={control}
        rules={{
          required: 'Email is required',
          pattern: {
            value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
            message: 'Enter a valid email address',
          },
        }}
      />
      {errors.email && (
        <Error>
          <SvgIcon icon={Icons.warning} />
          <span>{errors.email.message}</span>
        </Error>
      )}
    </FormField>
  );
}
