// apps/react-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-group-column/CheckboxGroupColumn.tsx
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-group-column.config';
import { Checkbox } from '@cocokits/react-checkbox';

export function CheckboxGroupColumn(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
      <i style={{ color: 'var(--checkbox-group-column-color)' }}>My hobbies</i>
      <Checkbox size={props.cckExampleArgs.size} value={1}>
        Comic books
      </Checkbox>
      <Checkbox size={props.cckExampleArgs.size} value={1}>
        Listen to music
      </Checkbox>
      <Checkbox size={props.cckExampleArgs.size} value={1}>
        Travel the world
      </Checkbox>
      <Checkbox size={props.cckExampleArgs.size} value={1}>
        Watch movies
      </Checkbox>
    </div>
  );
}

// apps/angular-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-group-column/checkbox-group-column.component.ts
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-checkbox';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-group-column.config';

@Component({
  standalone: true,
  selector: 'cck-checkbox-group-column',
  imports: [CheckboxComponent],
  template: `
    <div style="display: flex; flex-direction: column; gap: 12px;">
      <i style="color: var(--checkbox-group-column-color);">My hobbies</i>
      <cck-checkbox [size]="cckExampleArgs().size" [value]="1">Comic books</cck-checkbox>
      <cck-checkbox [size]="cckExampleArgs().size" [value]="1">Listen to music</cck-checkbox>
      <cck-checkbox [size]="cckExampleArgs().size" [value]="1">Travel the world</cck-checkbox>
      <cck-checkbox [size]="cckExampleArgs().size" [value]="1">Watch movies</cck-checkbox>
    </div>
  `,
  styles: ``,
})
export class CheckboxGroupColumnComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}
