// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/input-suffix-success/InputSuffixSuccess.tsx
import { useState } from 'react';

import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/input-suffix-success.config';
import { FormField, Hint, Input, Label, Suffix, SvgIcon } from '@cocokits/react-components';

export function InputSuffixSuccess(props: { cckExampleArgs: ExampleArgs }) {
  const [value, setValue] = useState('');
  
      
  return (
    <FormField>
      <Label>Confirm email</Label>
      <Input placeholder='Enter hello@cocokits.com' onChange={e => setValue(e.target.value)}/>
      <Suffix>
        { value === 'hello@cocokits.com' && <SvgIcon icon={Icons.checkCircle} color={props.cckExampleArgs.iconColor} size={props.cckExampleArgs.iconSize}/> }
      </Suffix>
      <Hint>Enter your email address again</Hint>
    </FormField>
  );
}

// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/input-suffix-success/input-suffix-success.component.ts
import { Component, computed, input, signal } from '@angular/core';

import {
  FormFieldComponent,
  HintComponent,
  InputComponent,
  LabelComponent,
  SuffixComponent,
  SvgIconComponent,
} from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/input-suffix-success.config';

@Component({
  selector: 'cck-input-suffix-success',
  imports: [FormFieldComponent, LabelComponent, InputComponent, SuffixComponent, HintComponent, SvgIconComponent],
  template: `
    <cck-form-field>
      <cck-label>Confirm email</cck-label>
      <input cck-input placeholder="Enter hello@cocokits.com" (input)="setValue($event)" />
      @if (isValid()) {
        <cck-suffix>
          <cck-svg-icon
            [icon]="Icons.checkCircle"
            [color]="cckExampleArgs().iconColor"
            [size]="cckExampleArgs().iconSize"></cck-svg-icon>
        </cck-suffix>
      }
      <cck-hint>Enter your email address again</cck-hint>
    </cck-form-field>
  `,
  styles: ``,
})
export class InputSuffixSuccessComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  protected readonly Icons = Icons;
  protected value = signal('');
  protected isValid = computed(() => this.value() === 'hello@cocokits.com');

  setValue(event: Event) {
    this.value.set((event.target as HTMLInputElement).value);
  }
}
