// apps/react-kits-doc/stories/ui-components/button/button/examples/copy-link-button/CopyLinkButton.tsx
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/copy-link-button.config';
import { Button, SvgIcon } from '@cocokits/react-components';

export function CopyLinkButton(props: {cckExampleArgs: ExampleArgs}) {

  return (
    <Button type={props.cckExampleArgs.buttonType}>
      <SvgIcon icon={Icons.link} />
      <span>Copy Link</span>
    </Button>
  );
}

// apps/angular-kits-doc/stories/ui-components/button/button/examples/copy-link-button/copy-link-button.component.ts
import { Component, input } from '@angular/core';

import { ButtonComponent, SvgIconComponent } from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/copy-link-button.config';

@Component({
  selector: 'cck-copy-link-button',
  imports: [ButtonComponent, SvgIconComponent],
  template: `
    <button cck-button [type]="cckExampleArgs().buttonType">
      <cck-svg-icon [icon]="Icons.link" />
      <span>Copy Link</span>
    </button>
  `,
})
export class CopyLinkButtonComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  public readonly Icons = Icons;
}
