// packages/react/form-field/src/lib/chip-list.tsx
/* eslint-disable max-lines-per-function */
'use client';
import { useEffect, useRef } from 'react';

import { hasNotValue } from '@cocokits/common-utils';
import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';

import Chip from './chip';
import { useFormStore } from './form-store';
import { useChipListStore } from './use-chip-list-store';

interface ChipListProps extends UIBaseComponentProps {
  /**
   * Sets the list of chips to be displayed in the component.
   * When this input is updated, the selection store is updated with the new chips.
   */
  chips?: string[];

  /** Determines whether a chip should be added when the input loses focus. */
  addOnBlur?: boolean;

  /** The placeholder text displayed in the input field. */
  placeholder?: string;

  /**
   * Disables the chip list, preventing user interaction.
   */
  disabled?: boolean;

  /** Calls, when the chip item that has been removed from the list. */
  onChipRemove?: (chip: string) => void;

  /** Calls, the chip item that has been added to the list. */
  onChipAdd?: (chip: string) => void;

  /** Calls, when the chip item that has been added to the list. */
  onChipsChange?: (chips: string[]) => void;
  
  className?: string;
  style?: React.CSSProperties;
}

export function ChipList(props: ChipListProps) {
  const formStore = useFormStore();
  const {chips, addChip, removeChip, setChips} = useChipListStore();
  const inputRef = useRef<HTMLInputElement>(null);

  const separatorKeysCodes = ['Enter'];

  const formDisabled = formStore?.useState((state) => state.disabled);
  const formWrapperElement = formStore?.useState((state) => state.formFieldWrapperElem);
  const size = formStore?.useState((state) => state.size);

  const disabled = props.disabled ?? formDisabled;
  
  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'chipList',
    props,
    extraHostElementClassConditions: [
      { if: disabled, classes: (cn) => [cn.disabled] },
      { if: !!props.className, classes: () => [props.className] },
    ]
  });

  useEffect(() => {
    if(!props.chips) {
      return;
    }
    setChips(props.chips);
  }, [props.chips]);

  // Register chipList into formSore 
  useEffect(() => {
    formStore?.deepUpdateComponent('chipList', {
      disabled: props.disabled,
      size: props.size,
    });
  }, [formStore, props.disabled, props.size]);

  // Unregister chipList into formSore 
  useEffect(() => {
    return () => {
      formStore?.unregisterComponent('chipList');
    };
  }, []);

  // Handle formFiled wrapper click, to focus on input
  useEffect(() => {
    const onFormFieldHostClick = () => {
      inputRef.current?.focus();
    };

    formWrapperElement?.addEventListener('click', onFormFieldHostClick);

    return () => {
      formWrapperElement?.removeEventListener('click', onFormFieldHostClick);
    };
  }, [formWrapperElement, inputRef.current]);

  
  const onInputKeyup = (e: React.KeyboardEvent<HTMLInputElement>) => {
    const value = e.currentTarget.value.trim();
    if (!separatorKeysCodes.includes(e.key) || hasNotValue(value)) {
      return;
    }
    const newChipsState = addChip(value);
    if(newChipsState) {
      props.onChipAdd?.(value);
      props.onChipsChange?.(newChipsState);
    }
    e.currentTarget.value = '';
  };

  const onInputBlur = (e: React.FocusEvent<HTMLInputElement>) => {
    const value = e.currentTarget.value.trim();

    if (!props.addOnBlur || hasNotValue(value)) {
      return;
    }
    const newChipsState = addChip(value);
    if(newChipsState) {
      props.onChipAdd?.(value);
      props.onChipsChange?.(newChipsState);
    }
    e.currentTarget.value = '';
  };

  const onRemoveChip = (chip: string) => {
    const newChipsState = removeChip(chip);
    if(newChipsState) {
      props.onChipRemove?.(chip);
      props.onChipsChange?.(newChipsState);
    }
  };

  return (
    <div className={hostClassNames} style={props.style}>
      {
        chips.map((chip, index) => (
          <Chip
            key={index}
            removable
            size={size}
            onRemove={() => onRemoveChip(chip)}>
            {chip}
          </Chip>
        ))
      }

      <input
        ref={inputRef}
        type="text"
        className={classNames.input}
        placeholder={props.placeholder}
        disabled={disabled}
        onKeyUp={onInputKeyup}
        onBlur={onInputBlur}
      />
    </div>
  );
}

ChipList.displayName = 'ChipList';
export default ChipList;

// packages/angular/form-field/src/lib/chip-list/chip-list.component.ts
/* eslint-disable @typescript-eslint/member-ordering */
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  Input,
  input,
  OnDestroy,
  output,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';
import { hasValue, toBooleanOrPresent } from '@cocokits/common-utils';

import { ChipComponent } from '../chip/chip.component';
import { injectFormFieldStore } from '../form-field.store';
import { SelectStore, SelectStoreService } from '../select.store';

@Component({
  standalone: true,
  imports: [ChipComponent],
  selector: 'cck-chip-list',
  templateUrl: './chip-list.component.html',
  styleUrls: ['./chip-list.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    {
      provide: SelectStore,
      useClass: SelectStoreService,
    },
  ],
  host: {
    '[class]': 'hostClassNames()',
    '(click)': 'onHostClick()',
  },
})
export class ChipListComponent<T = any> extends _UiBaseComponent<'chipList'> implements OnDestroy {
  protected readonly componentName = 'chipList';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.formFieldStore.state.disabled(), classes: this.classNames().disabled },
  ]);

  override size = computed(() => this._size() ?? this.formFieldStore.formField.size?.());

  protected formFieldStore = injectFormFieldStore();
  protected selectionStore = inject(SelectStore);
  private cd = inject(ChangeDetectorRef);

  private readonly separatorKeysCodes = ['Enter'];

  /** A function to determine the display value of each chip item. */
  @Input() displayBy: (item: T) => any = (item) => item;

  /**
   * Sets the list of chips to be displayed in the component.
   * When this input is updated, the selection store is updated with the new chips.
   */
  @Input() set chips(chips: T[]) {
    this.selectionStore.setSelection(chips);
  }
  /** Determines whether a chip should be added when the input loses focus. */
  addOnBlur = input(true);

  /** The placeholder text displayed in the input field. */
  placeholder = input<string>();

  /** Disables the chip list, preventing user interaction. */
  disabled = input(undefined, { transform: toBooleanOrPresent });

  /** Emits the current list of selected chips whenever a change occurs. */
  change = output<T[]>();

  /** Emits the chip item that has been removed from the list. */
  remove = output<T>();

  /** Emits the chip item that has been added to the list. */
  add = output<T>();

  private inputRef = viewChild.required<ElementRef<HTMLInputElement>>('input');

  __onFormFieldWrapperClick = effect((onCleanup) => {
    const callback = () => this.onHostClick();

    this.formFieldStore.formField.wrapperElem()?.nativeElement.addEventListener('click', callback);

    onCleanup(() => {
      this.formFieldStore.formField.wrapperElem()?.nativeElement.removeEventListener('click', callback);
    });
  });

  constructor() {
    super();

    this.selectionStore.resetWithOption({ multiple: true });
    this.formFieldStore.registerComponent('chipList', this, this.cd);
  }

  protected onHostClick() {
    this.inputRef().nativeElement.focus();
  }

  protected onChipClick(e: MouseEvent) {
    e.stopPropagation();
  }

  protected onInputBlur() {
    const inputElem = this.inputRef().nativeElement;
    const value = inputElem.value.trim();

    if (this.addOnBlur() && hasValue(value)) {
      this.selectionStore.select(value);
      inputElem.value = '';
    }
  }

  protected onKeyup(e: KeyboardEvent) {
    const inputElem = this.inputRef().nativeElement;
    const value = inputElem.value.trim();

    if (this.separatorKeysCodes.includes(e.key) && hasValue(value)) {
      this.selectionStore.select(value);
      inputElem.value = '';
    }
  }

  protected onChipRemove(chip: T) {
    this.selectionStore.deselect(chip);
  }

  ngOnDestroy() {
    this.formFieldStore.unregisterComponent(this, this.cd);
  }
}

@for (chip of selectionStore.selectedItems(); track displayBy(chip)) {
  <cck-chip [removable]="true" [size]="_effectedSize()" (remove)="onChipRemove(chip)" (click)="onChipClick($event)">
    {{displayBy(chip)}}
  </cck-chip>
}

<input
  #input
  type="text"
  [disabled]="formFieldStore.state.disabled()"
  [class]="classNames().input"
  [placeholder]="placeholder()"
  (keyup)="onKeyup($event)"
  (blur)="onInputBlur()"
/>
