// packages/react/avatar/src/lib/avatar/avatar.tsx
import React, { useLayoutEffect } from 'react';

import { hasNotValue, hasValue } from '@cocokits/common-utils';
import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';

export interface AvatarProps extends UIBaseComponentProps {
  /**
   * Source URL for the avatar image.
   */
  src?: string;

  /**
   * Alternative text for the avatar image for accessibility purposes.
   */
  alt?: string;

  /**
   * Source URL for a fallback image to display when the primary image fails to load.
   */
  fallbackSrc?: string;

  /**
   * Source URL for a placeholder image to display while the primary image is loading.
   */
  placeholderSrc?: string;

  /**
   * Text label to display when no image source is provided.
   */
  label?: string;

  /**
   * Whether the avatar should be clickable.
   * @defaultValue true
   */

  clickable?: boolean;

  /**
   * Use this template to display custom content inside the avatar component.
   * This is useful for advanced scenarios, such as displaying multiple images as a single avatar,
   * or having full control over the avatar's image rendering and logic.
   *
   * @note:
   * When a custom template is provided, all default content, css selectors, styles,
   * and component configurations related to child elements will be removed.
   * Only your custom template and the host component will be rendered.
   */
  contentTemp?: React.ReactNode;
}

export function Avatar({ type, size, color, additional, clickable = true, ...restProps }: AvatarProps) {
  const withImage = !restProps.contentTemp && hasValue(restProps.src);
  const withLabel = !restProps.contentTemp && hasNotValue(restProps.src) && hasValue(restProps.label);

  const [imageStatus, setImageStatus] = React.useState<'idle' | 'loading' | 'loaded' | 'error'>('loading');

  const canShowImg = withImage && imageStatus !== 'error';
  const canShowPlaceholder = withImage && imageStatus === 'loading' && hasValue(restProps.placeholderSrc);
  const canShowFallback = withImage && imageStatus === 'error' && hasValue(restProps.fallbackSrc);
  const canShowLabel = withLabel && hasValue(restProps.label);

  useLayoutEffect(() => {
    setImageStatus(withImage ? 'loading' : 'idle');
  }, [restProps.src]);

  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'avatar',
    props: { type, size, color, additional },
    extraHostElementClassConditions: [
      { if: imageStatus === 'loading', classes: (cn) => [cn.loading] },
      { if: imageStatus === 'loaded', classes: (cn) => [cn.loaded] },
      { if: imageStatus === 'error', classes: (cn) => [cn.fallback] },
      { if: withImage, classes: (cn) => [cn.withImage] },
      { if: withLabel, classes: (cn) => [cn.withLabel] },
      { if: !!restProps.contentTemp, classes: (cn) => [cn.withCustomContent] },
      { if: clickable, classes: (cn) => [cn.clickable] },
    ],
  });

  return (
    <div className={hostClassNames}>
      {restProps.contentTemp || (
        <>
          {canShowImg && (
            <img
              className={classNames.image}
              src={restProps.src}
              alt={restProps.alt}
              style={{ display: imageStatus === 'loaded' ? 'block' : 'none' }}
              onLoad={() => setImageStatus('loaded')}
              onError={() => setImageStatus('error')}
            />
          )}

          {canShowPlaceholder && (
            <img className={classNames.placeholderImage} src={restProps.placeholderSrc} alt={restProps.alt} />
          )}

          {canShowFallback && (
            <img className={classNames.fallbackImage} src={restProps.fallbackSrc} alt={restProps.alt} />
          )}

          {canShowLabel && <span className={classNames.label}>{restProps.label}</span>}
        </>
      )}
    </div>
  );
}

Avatar.displayName = 'Avatar';
export default Avatar;

// packages/angular/avatar/src/lib/avatar/avatar.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChild,
  effect,
  input,
  signal,
  TemplateRef,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';
import { hasNotValue, hasValue } from '@cocokits/common-utils';

import { AvatarTemplateDirective } from './avatar.tmpl-directive';

@Component({
  standalone: true,
  imports: [CommonModule],
  selector: 'cck-avatar',
  templateUrl: './avatar.component.html',
  styleUrls: ['./avatar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
  },
})
export class AvatarComponent extends _UiBaseComponent<'avatar'> {
  protected readonly componentName = 'avatar';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.imgStatus() === 'loading', classes: this.classNames().loading },
    { if: this.imgStatus() === 'loaded', classes: this.classNames().loaded },
    { if: this.imgStatus() === 'error', classes: this.classNames().fallback },
    { if: this.wihImage(), classes: this.classNames().withImage },
    { if: this.wihLabel(), classes: this.classNames().withLabel },
    { if: this.contentTemp(), classes: this.classNames().withCustomContent },
    { if: this.contentTemp(), classes: this.classNames().withCustomContent },
    { if: this.clickable(), classes: this.classNames().clickable },
  ]);

  /**
   * Source URL for the avatar image.
   * @storybook argType will be overridden by storybook
   */
  public src = input<string>();

  /**
   * Alternative text for the avatar image for accessibility purposes.
   * @storybook argType will be overridden by storybook
   */
  public alt = input<string>();

  /**
   * Source URL for a fallback image to display when the primary image fails to load.
   * @storybook argType will be overridden by storybook
   */
  public fallbackSrc = input<string>();

  /**
   * Source URL for a placeholder image to display while the primary image is loading.
   * @storybook argType will be overridden by storybook
   */
  public placeholderSrc = input<string>();

  /**
   * Text label to display when no image source is provided.
   * @storybook argType will be overridden by storybook
   */
  public label = input<string>();

  /**
   * Whether the avatar should be clickable. Defaults to true.
   * @storybook argType will be overridden by storybook
   */
  public clickable = input<boolean>(true);

  private contentTemp = contentChild(AvatarTemplateDirective, { read: TemplateRef<HTMLElement> });
  private defaultTemp = viewChild.required<TemplateRef<HTMLElement>>('defaultTemp');

  protected wihImage = computed(() => !this.contentTemp() && hasValue(this.src()));
  protected wihLabel = computed(() => !this.contentTemp() && hasNotValue(this.src()) && hasValue(this.label()));

  protected template = computed(() => this.contentTemp() ?? this.defaultTemp());

  protected imgStatus = signal<'idle' | 'loading' | 'loaded' | 'error'>('idle');

  protected canShowImg = computed(() => this.wihImage() && this.imgStatus() !== 'error');

  protected canShowPlaceholder = computed(
    () => this.wihImage() && this.imgStatus() === 'loading' && hasValue(this.placeholderSrc())
  );

  protected canShowFallback = computed(
    () => this.wihImage() && this.imgStatus() === 'error' && hasValue(this.fallbackSrc())
  );

  protected canShowLabel = computed(() => this.wihLabel() && hasValue(this.label()));

  private __setImageLoadingState = effect(
    () => {
      this.imgStatus.set(this.wihImage() ? 'loading' : 'idle');
    },
    { allowSignalWrites: true }
  );
}

<ng-container *ngTemplateOutlet="template()"></ng-container>

<ng-template #defaultTemp>
  @if(canShowImg()) {
    <img
      [class]="classNames().image"
      [src]="src()"
      [alt]="alt()"
      [style.display]="imgStatus() === 'loaded' ? 'block' : 'none'"
      (load)="imgStatus.set('loaded')"
      (error)="imgStatus.set('error')"
      (loadend)="imgStatus.set('loaded')"
    />
  }

  @if(canShowPlaceholder()) {
    <img
      [class]="classNames().placeholderImage"
      [src]="placeholderSrc()"
      [alt]="alt()"
    />
  }

  @if(canShowFallback()) {
    <img
      [class]="classNames().fallbackImage"
      [src]="fallbackSrc()"
      [alt]="alt()"
    />
  }

  @if(canShowLabel()) {
    <span [class]="classNames().label">{{label()}}</span>
  }
</ng-template>
