// packages/angular/form-field/src/lib/chip/chip.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  InputSignal,
  output,
  OutputEmitterRef,
  ViewEncapsulation,
} from '@angular/core';

import { IconButtonComponent } from '@cocokits/angular-button';
import { _UiBaseComponent } from '@cocokits/angular-core';
import { SvgIconComponent } from '@cocokits/angular-icon';
import { toBooleanOrPresent } from '@cocokits/common-utils';
import { ThemeSvgIcon } from '@cocokits/core';

import { injectFormFieldStore } from '../form-field.store';

@Component({
  standalone: true,
  imports: [SvgIconComponent, IconButtonComponent],
  selector: 'cck-chip',
  templateUrl: './chip.component.html',
  styleUrls: ['./chip.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
  },
})
export class ChipComponent extends _UiBaseComponent<'chip'> {
  protected readonly componentName = 'chip';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.disabled() ?? this.formFieldStore.state.disabled(), classes: this.classNames().disabled },
    { if: this.removable(), classes: this.classNames().removable },
  ]);

  protected formFieldStore = injectFormFieldStore();

  protected removeIcon: ThemeSvgIcon;

  // region ---------------- INPUTS ----------------
  /** Determines whether or not the chip displays the remove styling and emits (removed) events. */
  removable: InputSignal<boolean | undefined> = input<boolean>();

  /**
   * Whether the chip is disabled.
   * @storybook argType will be overridden by storybook
   */
  disabled = input(undefined, { transform: toBooleanOrPresent });
  // endregion

  // region ---------------- OUTPUTS ----------------
  /** Emitted when a chip is to be removed. */
  remove: OutputEmitterRef<void> = output<void>();
  // endregion

  constructor() {
    super();

    const removeIcon = this.themeConfig.components.chip?.templates?.chipRemoveIcon;

    if (!removeIcon) {
      throw new Error('`chipRemoveIcon` has not defined in `ThemeConfig` of selected theme');
    }
    this.removeIcon = removeIcon;
  }

  protected onRemoveBtnClick() {
    this.remove.emit();
  }
}

<div [class]="classNames().contentWrapper">
  <ng-content></ng-content>
</div>

@if(removable()) {
  <div [class]="classNames().removeIconWrapper">
    <button cck-icon-button type="null" size="null" color="null" (click)="onRemoveBtnClick()">
      <cck-svg-icon [icon]="removeIcon"></cck-svg-icon>
    </button>
  </div>
}

// packages/react/form-field/src/lib/chip.tsx
'use client';
import { useContext } from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { IconButton } from '@cocokits/react-button';
import { ThemeConfigContext, useUiBaseComponentConfig } from '@cocokits/react-core';
import { SvgIcon } from '@cocokits/react-icon';

import { useFormStore } from './form-store';

interface ChipProps extends UIBaseComponentProps {
  /**
   * Whether the chip is disabled.
   */
  disabled?: boolean;

  /**
   * Determines whether or not the chip displays the remove styling and emits (removed) events.
   */
  removable?: boolean;

  /**
   * Will called when the chip remove icon has been clicked.
   */
  onRemove?: () => void;
  children?: React.ReactNode | React.ReactNode[];
  className?: string;
  style?: React.CSSProperties;
}

export function Chip(props: ChipProps) {
  const formStore = useFormStore();
  const themeConfig = useContext(ThemeConfigContext);

  const formDisabled = formStore?.useState((state) => state.disabled);
  const disabled = props.disabled ?? formDisabled;
  
  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'chip',
    props,
    extraHostElementClassConditions: [
      { if: disabled, classes: (cn) => [cn.disabled] },
      { if: props.removable, classes: (cn) => [cn.removable] },
      { if: !!props.className, classes: () => [props.className] },
    ]
  });

  const removeIcon = themeConfig?.components.chip?.templates?.chipRemoveIcon;

  if (!removeIcon) {
    throw new Error('`chipRemoveIcon` has not defined in `ThemeConfig` of selected theme');
  }

  const onRemoveBtnClick = () => {
    props.onRemove?.();
  };

  return (
    <div className={hostClassNames} style={props.style} onClick={(e) => e.stopPropagation()}>
      <div className={classNames.contentWrapper}>
        {props.children}
      </div>

      {props.removable && (
        <div className={classNames.removeIconWrapper}>
          <IconButton
            type={null}
            size={null}
            color={null}
            onClick={onRemoveBtnClick}>
            <SvgIcon icon={removeIcon} />
          </IconButton>
        </div>
      )}
    </div>
  );
}

Chip.displayName = 'Chip';
export default Chip;
