// packages/angular/form-field/src/lib/label/label.component.ts
import { ChangeDetectionStrategy, Component, computed, ViewEncapsulation } from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';

import { injectFormFieldStore } from '../form-field.store';

@Component({
  standalone: true,
  imports: [],
  selector: 'cck-label',
  templateUrl: './label.component.html',
  styleUrls: ['./label.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
  },
})
export class LabelComponent extends _UiBaseComponent<'label'> {
  protected readonly componentName = 'label';
  protected extraHostElementClassConditions = computed(() => []);

  protected store = injectFormFieldStore();
}

<label [class]="classNames().labelTag" [for]="for()">
  <ng-content></ng-content>

  @if(!store.state.hideRequiredMarker() && store.state.required()) {
    <span [class]="classNames().requiredMarker">*</span>
  }
</label>

// packages/react/form-field/src/lib/label.tsx
'use client';
import { useEffect } from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';

import { useFormStore } from './form-store';

interface LabelProps extends UIBaseComponentProps {
  children?: React.ReactNode | React.ReactNode[];
  className?: string;
}

export function Label(props: LabelProps) {
  const formStore = useFormStore();

  const hideRequiredMarker = formStore?.useState((state) => state.hideRequiredMarker);
  const required = formStore?.useState((state) => state.required);

  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'label',
    props,
  });

  useEffect(() => {
    const template = (
      <div className={`${hostClassNames} ${props.className ?? ''}`}>
        <label className={classNames.labelTag}>
          {props.children}
    
          {!hideRequiredMarker && required && <span className={classNames.requiredMarker}>*</span>}
        </label>
      </div>
    );

    formStore?.updateComponent('label', {template});
  }, [props.children,hideRequiredMarker, required]);

  useEffect(() => {
    return () => formStore?.unregisterComponent('label');
  }, []);

  return <></>;
}

Label.displayName = 'Label';
export default Label;
