// packages/angular/form-field/src/lib/option/option.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input, ViewEncapsulation } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-checkbox';
import { _UiBaseComponent } from '@cocokits/angular-core';
import { SvgIconComponent } from '@cocokits/angular-icon';
import { isNotNullish, isNullish, toBooleanOrPresent } from '@cocokits/common-utils';

import { OptionGroupComponent } from '../option-group/option-group.component';
import { injectSelectStore, SelectTriggerSource } from '../select.store';
import { SelectComponent } from '../select/select.component';

@Component({
  standalone: true,
  imports: [CheckboxComponent, SvgIconComponent],
  selector: 'cck-option',
  templateUrl: './option.component.html',
  styleUrls: ['./option.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
    '(click)': 'onHostClick($event)',
  },
})
export class OptionComponent<T = any> extends _UiBaseComponent<'option'> {
  protected readonly componentName = 'option';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.effectedDisabled(), classes: this.classNames().disabled },
    { if: this.isSelected(), classes: this.classNames().selected },
    { if: this.selectStore.isMultiple(), classes: this.classNames().multiple },
    { if: !this.selectStore.isMultiple(), classes: this.classNames().single },
  ]);

  override _effectedSize = computed(() => this.size() ?? this.selectComp?._effectedSize());
  protected effectedDisabled = computed(() => this.disabled() ?? this.optionGroupComp?.disabled() ?? false);

  private optionGroupComp = inject(OptionGroupComponent, { optional: true });
  private selectComp = inject(SelectComponent, { optional: true });
  protected selectStore = injectSelectStore<T>();

  /**
   * Whether the input is disabled.
   */
  public disabled = input(null, { transform: toBooleanOrPresent });

  /**
   * Value of the select control.
   */
  public value = input<T>();

  protected isSelected = computed(() => {
    const value = this.value();
    return isNotNullish(value) ? this.selectStore.isSelected(value)() : false;
  });

  protected onHostClick(e: Event) {
    e.stopPropagation();

    if (this.effectedDisabled()) {
      return;
    }

    const value = this.value();

    if (this.selectStore.isMultiple()) {
      if (isNullish(value)) {
        return;
      }
      this.selectStore.toggle(value, { triggerSource: SelectTriggerSource.FromOption });
      return;
    }

    isNullish(value)
      ? this.selectStore.clear({ triggerSource: SelectTriggerSource.FromOption })
      : this.selectStore.select(value, { triggerSource: SelectTriggerSource.FromOption });

    this.selectStore.renderedOverlay?.overlayRef.close();
  }

  protected onCheckboxClick(checked: boolean) {
    const value = this.value();

    if (isNullish(value)) {
      return;
    }

    checked
      ? this.selectStore.select(value, { triggerSource: SelectTriggerSource.FromOption })
      : this.selectStore.deselect(value, { triggerSource: SelectTriggerSource.FromOption });
  }
}

@if(selectStore.isMultiple()) {
  <div [class]="classNames().multipleWrapper">
    <cck-checkbox [checked]="isSelected()" (change)="onCheckboxClick($event.checked)"></cck-checkbox>
  </div>

}

<div [class]="classNames().contentWrapper">
  <ng-content></ng-content>
</div>



@if(isSelected() && !selectStore.isMultiple() && themeConfig.components.option?.templates?.optionSelectedIcon) {
  <div [class]="classNames().selectedCheckmark">
    @if(themeConfig.components.option?.templates?.optionSelectedIcon) {
      <cck-svg-icon [icon]="themeConfig.components.option?.templates!.optionSelectedIcon!"></cck-svg-icon>
    }
  </div>
}

// packages/react/form-field/src/lib/option.tsx
'use client';
import { useContext } from "react";

import { isNullish } from "@cocokits/common-utils";
import { UIBaseComponentProps } from "@cocokits/core";
import { Checkbox } from "@cocokits/react-checkbox";
import { ThemeConfigContext, useUiBaseComponentConfig } from "@cocokits/react-core";
import { SvgIcon } from "@cocokits/react-icon";
import { useOverlayRef } from "@cocokits/react-overlay";

import { useFormStore } from "./form-store";
import { OptionGroupContext } from "./option-group";
import { useSelectStore } from "./select-store";

export interface OptionProps<T = unknown> extends UIBaseComponentProps {
  disabled?: boolean;
  /**
   * Value of the select control.
   */
  value: T;

  children?: React.ReactNode;
}

export const Option = <T,>(props: OptionProps<T>) => {

  const overlayRef = useOverlayRef();
  const optionGroup = useContext(OptionGroupContext);
  const themeConfig = useContext(ThemeConfigContext);
  const optionSelectedIcon = themeConfig?.components.option?.templates?.optionSelectedIcon;

  const selectStore = useSelectStore<T>();
  const formStore = useFormStore();
  const isSelected = selectStore?.useIsSelected(props.value);
  const isMultiple = selectStore?.useState(state => state.isMultiple);
  
  const formDisabled = formStore?.useState((state) => state.disabled);
  const disabled = props.disabled ?? optionGroup?.disabled ?? formDisabled;

  const canShowSelectedIcon = isSelected && optionSelectedIcon && !isMultiple;

  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'option',
    props,
    extraHostElementClassConditions: [
      { if: disabled, classes: (cn) => [cn.disabled] },
      { if: isSelected, classes: (cn) => [cn.selected] },
      { if: isMultiple, classes: (cn) => [cn.multiple] },
      { if: !isMultiple, classes: (cn) => [cn.single] },
    ],
  });


  const onHostClick = (e: React.MouseEvent<HTMLElement>) => {
    e.stopPropagation();

    if(disabled) {
      return;
    }

    if(isMultiple) {
      if(isNullish(props.value)) {
        return;
      }

      selectStore?.toggle(props.value);
      return;
    }

    isNullish(props.value)
      ? selectStore?.clear()
      : selectStore?.select(props.value);

    overlayRef.close();
  };

  return (
    <div className={hostClassNames} onClick={onHostClick}>
      {
        isMultiple &&
        <div className={classNames.multipleWrapper}>
          <Checkbox
            checked={isSelected}
            disabled={disabled}
            onChange={() => selectStore?.toggle(props.value)}
          />
        </div>
      }

      <div className={classNames.contentWrapper}>
        {props.children}
      </div>

      {canShowSelectedIcon && (
        <div className={classNames.selectedCheckmark}>
          <SvgIcon icon={optionSelectedIcon} />
        </div>
      )}
    </div>
  );

};

Option.displayName = 'Option';

export default Option;
