// apps/react-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-group-row/CheckboxGroupRow.tsx
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-group-row.config';
import { Checkbox } from '@cocokits/react-checkbox';

export function CheckboxGroupRow(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <div>
      <i style={{ color: 'var(--checkbox-group-column-color)' }}>Favorite food</i>
      <div style={{ display: 'flex', flexDirection: 'row', gap: '12px', marginTop: '10px' }}>
        <Checkbox size={props.cckExampleArgs.size} value={1}>
          Pizza
        </Checkbox>
        <Checkbox size={props.cckExampleArgs.size} value={1}>
          Pasta
        </Checkbox>
        <Checkbox size={props.cckExampleArgs.size} value={1}>
          Fruits
        </Checkbox>
      </div>
    </div>
  );
}

// apps/angular-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-group-row/checkbox-group-row.component.ts
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-checkbox';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-group-row.config';

@Component({
  standalone: true,
  selector: 'cck-checkbox-group-row',
  imports: [CheckboxComponent],
  template: `
    <div>
      <i style="color: var(--checkbox-group-column-color);">Favorite food</i>
      <div style="display: flex; flex-direction: row; gap: 12px; marginTop: 10px;">
        <cck-checkbox [size]="cckExampleArgs().size" [value]="1">Pizza</cck-checkbox>
        <cck-checkbox [size]="cckExampleArgs().size" [value]="1">Pasta</cck-checkbox>
        <cck-checkbox [size]="cckExampleArgs().size" [value]="1">Fruits</cck-checkbox>
      </div>
    </div>
  `,
  styles: ``,
})
export class CheckboxGroupRowComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}
