// packages/angular/badge/src/lib/badge-container/badge-container.component.ts
import { ChangeDetectionStrategy, Component, computed, input, ViewEncapsulation } from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';

@Component({
  imports: [],
  selector: 'cck-badge-container',
  templateUrl: './badge-container.component.html',
  styleUrls: ['./badge-container.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
    '[style.--cck-badge-radius]': 'radius()',
  },
})
export class BadgeContainerComponent extends _UiBaseComponent<'badgeContainer'> {
  protected readonly componentName = 'badgeContainer';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.position() === 'top-left', classes: this.classNames().topLeft },
    { if: this.position() === 'top-right', classes: this.classNames().topRight },
    { if: this.position() === 'bottom-left', classes: this.classNames().bottomLeft },
    { if: this.position() === 'bottom-right', classes: this.classNames().bottomRight },
    { if: this.offset() && this.offset()?.[0] && this.offset()?.[1], classes: this.classNames().customOffset },
  ]);

  /** Position of the badge. */
  position = input<'top-left' | 'top-right' | 'bottom-left' | 'bottom-right'>('top-right');

  /**
   * [horizontal, vertical] pixel adjustment for badge position.
   * it's allow you to take control of badge positioning.
   * @example ['10px', '20px']
   */
  offset = input<[string, string]>();

  /**
   * Controls the corner rounding of the component. Accepts any valid CSS border-radius value
   * including pixels (e.g. "12px"), percentages (e.g. "50%").
   * Percentage values are relative to the component's dimensions.
   * useful for when the content is curved such as avatars.
   */
  radius = input<string>('0px');

  protected transformBadgeWrapper = computed(() => {
    const offset = this.offset();
    if (!offset) {
      return null;
    }
    return `translate(${offset[0]}, ${offset[1]})`;
  });
}

<ng-content/>

<div
  [class]="classNames().badgeWrapper"
  [style.transform]="transformBadgeWrapper()"
  >
  <ng-content select="cck-badge"></ng-content>
</div>

// packages/react/badge/src/lib/badge-container/badge-container.tsx
import { CSSProperties, ReactNode } from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';
import { useSlotChildren } from '@cocokits/react-utils';

export interface BadgeContainerProps extends UIBaseComponentProps {

  /** Position of the badge. */
  position?: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';

  /**
   * [horizontal, vertical] pixel adjustment for badge position.
   * Allows control over badge positioning.
   * @example ['10px', '20px']
   */
  offset?: [string, string];

  /**
   * Controls the corner rounding of the component. Accepts any valid CSS border-radius value
   * including pixels (e.g. "12px"), percentages (e.g. "50%").
   * Percentage values are relative to the component's dimensions.
   * Useful for when the content is curved such as avatars.
   */
  radius?: string;

  /**
   * Content to display inside the badge container with the badge component
   * This can be any valid ReactNode, such as text, images, or other components
   */
  children: ReactNode[];

  /**
   * A custom class name that can be used to apply additional styles to the component.
   */
  className?: string;
  /**
   * An object containing inline styles that can be used to customize the appearance of the component.
   */
  style?: CSSProperties;
}

export const BadgeContainer = ({
  position = 'top-left',
  offset,
  radius = '0px',
  children,
  className,
  style,
  type,
  size,
  color,
  additional
}: BadgeContainerProps) => {
  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'badgeContainer',
    props: { type, size, color, additional },
    extraHostElementClassConditions: [
      { if: !!className, classes: () => [className] },
      { if: position === 'top-left', classes: (cn) => [cn.topLeft] },
      { if: position === 'top-right', classes: (cn) => [cn.topRight] },
      { if: position === 'bottom-left', classes: (cn) => [cn.bottomLeft] },
      { if: position === 'bottom-right', classes: (cn) => [cn.bottomRight] },
      { if: offset && !!offset[0] && !!offset[1], classes: (cn) => [cn.customOffset] },
    ],
  });

  const transformBadgeWrapper = (offset && offset[0] && offset[1]) ? `translate(${offset[0]}, ${offset[1]})` : undefined;
  const [badgeChild, restChildren] = useSlotChildren(children, 'Badge');

  return (
    <div className={hostClassNames} style={{ ...style, '--cck-badge-radius': radius } as CSSProperties}>
      {restChildren}

      <div
        className={classNames.badgeWrapper}
        style={{ transform: transformBadgeWrapper }}
      >
        {badgeChild}
      </div>
    </div>
  );
};

BadgeContainer.displayName = 'BadgeContainer';
export default BadgeContainer;
