// apps/react-kits-doc/stories/ui-components/button/button/examples/stack-horizontal-button/StackHorizontalButton.tsx
import styled from 'styled-components';

import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/stack-horizontal-button.config';
import { Button } from '@cocokits/react-components';

export function StackHorizontalButton(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <HostStyles>
      <Button
        type={props.cckExampleArgs.firstButtonType}
        size={props.cckExampleArgs.firstButtonSize}
        color={props.cckExampleArgs.firstButtonColor}>
        Cancel
      </Button>

      <Button
        type={props.cckExampleArgs.secondButtonType}
        size={props.cckExampleArgs.secondButtonSize}
        color={props.cckExampleArgs.secondButtonColor}>
        Confirm
      </Button>
    </HostStyles>
  );
}

const HostStyles = styled.div`
  display: flex;
  gap: 12px;
`;

// apps/angular-kits-doc/stories/ui-components/button/button/examples/stack-horizontal-button/stack-horizontal-button.component.ts
import { Component, input } from '@angular/core';

import { ButtonComponent } from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/stack-horizontal-button.config';

@Component({
  selector: 'cck-stack-horizontal-button',
  imports: [ButtonComponent],
  template: `
    <button
      cck-button
      [type]="cckExampleArgs().firstButtonType"
      [size]="cckExampleArgs().firstButtonSize"
      [color]="cckExampleArgs().firstButtonColor">
      Cancel
    </button>

    <button
      cck-button
      [type]="cckExampleArgs().secondButtonType"
      [size]="cckExampleArgs().secondButtonSize"
      [color]="cckExampleArgs().secondButtonColor">
      Confirm
    </button>
  `,
  styles: `
    :host {
      display: flex;
      gap: 12px;
    }
  `,
})
export class StackHorizontalButtonComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}
