// apps/react-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-box-selection/CheckboxBoxSelection.tsx
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-box-selection.config';
import { Checkbox } from '@cocokits/react-components';

import { Styled } from './CheckboxBoxSelection.styled';

export function CheckboxBoxSelection(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <Styled.Container>
      <Styled.Box>
        <Checkbox value={1}>Vegetarian</Checkbox>
      </Styled.Box>
      <Styled.Box>
        <Checkbox value={2}>Gluten-Free</Checkbox>
      </Styled.Box>
    </Styled.Container>
  );
}

// apps/angular-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-box-selection/checkbox-box-selection.component.ts
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-box-selection.config';

@Component({
  selector: 'cck-checkbox-box-selection',
  imports: [CheckboxComponent],
  templateUrl: './checkbox-box-selection.component.html',
  styleUrls: ['./checkbox-box-selection.component.scss'],
})
export class CheckboxBoxSelectionComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}

<cck-checkbox class="checkbox__box" [value]="1">
    Vegetarian
</cck-checkbox>
<cck-checkbox class="checkbox__box" [value]="2">
    Gluten-Free
</cck-checkbox>
