// packages/angular/tabs/src/lib/tabs/tabs.component.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  AfterContentInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChildren,
  effect,
  inject,
  Input,
  input,
  output,
  untracked,
  ViewEncapsulation,
} from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';
import { Animation, hasValue } from '@cocokits/common-utils';

import { TabComponent } from '../tab/tab.component';
import { TabsFeatureStore } from '../tabs.feature-store';
import { TabSelectionChangeEvent } from '../tabs.model';

@Component({
  imports: [NgTemplateOutlet],
  selector: 'cck-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
  },
  providers: [TabsFeatureStore],
})
export class TabsComponent<TValue = unknown> extends _UiBaseComponent<'tabs'> implements AfterContentInit {
  private featStore = inject(TabsFeatureStore);

  protected readonly componentName = 'tabs';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.headerAlign() === 'left', classes: this.classNames().alignLeft },
    { if: this.headerAlign() === 'right', classes: this.classNames().alignRight },
    { if: this.headerAlign() === 'center', classes: this.classNames().alignCenter },
    { if: this.headerAlign() === 'stretch', classes: this.classNames().alignStretch },
  ]);

  private _selectedIndex: number | undefined;
  /**
   * The index of the currently selected tab.
   * If `selected` is provided, the value of `selectedIndex` will be ignored.
   * @default 0
   */
  @Input() public set selectedIndex(index: number) {
    this._selectedIndex = index;
    this._updateSelected();
  }

  private _selectedValue: TValue | undefined;
  /**
   * The value of the currently selected tab.
   * If not provided, the `selectedIndex` will be used, and if `selectedIndex` is not provided, the first tab will be selected by default.
   */
  @Input() public set selected(value: TValue) {
    this._selectedValue = value;
    this._updateSelected();
  }

  /**
   * Whether to hide the content of the tabs when they are not selected.
   * @default false
   */
  public hideContent = input<boolean>(false);

  /**
   * Whether to disable the animation when switching between tabs.
   * @default false
   */
  public instantAnimation = input<boolean>(false);

  /**
   * The alignment of the tab headers.
   * @default 'left'
   */
  public headerAlign = input<'left' | 'center' | 'right' | 'stretch'>('left');

  /**
   * Emitter for the selected tab change event.
   * IIt will return only the value of the selected tab and you can combine it with `selected` to activate 2way data binding.
   */
  public selectedChange = output<TValue>();

  /**
   * Emitter for the selected index change event.
   * It will return only the index of the selected tab and you can combine it with `selectedIndex` to activate 2way data binding.
   */
  public selectedIndexChange = output<number>();

  /**
   * Emitter for the selection change event.
   * event is an object with the new and previous selected index and value.
   */
  public change = output<TabSelectionChangeEvent<TValue>>();

  protected tabComponents = contentChildren(TabComponent);

  protected selectedTabComponent = computed(() => {
    return this.tabComponents().find((tab) => this.featStore.selectedId() === tab._id);
  });

  private __dispatchChanges = effect(() => {
    const selectedId = this.featStore.selectedId();
    untracked(async () => {
      const prevuesSelectedId = this.featStore.prevuesSelectedId();
      const prevuesTabComponent = this.tabComponents().find((tab) => tab._id === prevuesSelectedId);
      const prevuesSelectedIndex = this.tabComponents().findIndex((tab) => tab._id === prevuesSelectedId);
      const prevuesSelectedValue = prevuesTabComponent?._value();

      const selectedTabComponent = this.selectedTabComponent();
      const selectedIndex = this.tabComponents().findIndex((tab) => tab._id === selectedId);
      const selectedValue = selectedTabComponent?._value();

      if (!selectedTabComponent) {
        return;
      }

      this.selectedChange.emit(selectedValue);
      this.selectedIndexChange.emit(selectedIndex);
      this.change.emit({
        previousIndex: prevuesSelectedIndex,
        previousValue: prevuesSelectedValue,
        index: selectedIndex,
        value: selectedValue,
      });

      if (!this.instantAnimation() && prevuesTabComponent) {
        const animationRef = Animation.getOrCreateInstance(selectedTabComponent._indicatorElemRef().nativeElement);

        selectedTabComponent._indicatorElemRef().nativeElement.style.removeProperty('display');
        const prevuesTabReact = prevuesTabComponent._indicatorElemRef().nativeElement.getBoundingClientRect();
        const newTabReact = selectedTabComponent._indicatorElemRef().nativeElement.getBoundingClientRect();

        animationRef
          .setDimension({ width: prevuesTabReact.width, height: prevuesTabReact.height })
          .setTranslate({ x: prevuesTabReact.left - newTabReact.left, y: prevuesTabReact.top - newTabReact.top })
          .applyImmediately();

        await animationRef
          .setDimension({ width: newTabReact.width, height: newTabReact.height })
          .setTranslate({ x: 0, y: 0 })
          .animate({ duration: 300 });

        selectedTabComponent._indicatorElemRef().nativeElement.style.removeProperty('width');
        selectedTabComponent._indicatorElemRef().nativeElement.style.removeProperty('height');
        selectedTabComponent._indicatorElemRef().nativeElement.style.removeProperty('transform');
      }
    });
  });

  ngAfterContentInit() {
    this._updateSelected();
  }

  public _updateSelected() {
    if (this.tabComponents().length === 0) {
      return;
    }

    if (hasValue(this._selectedValue)) {
      const selectedTab =
        this.tabComponents().find((tab) => tab.value() === this._selectedValue) ?? this.tabComponents()[0];
      this.featStore.selectTabById(selectedTab._id);
      return;
    }

    const selectedTabByIndex =
      this.tabComponents().find((_, index) => index === this._selectedIndex) ?? this.tabComponents()[0];
    this.featStore.selectTabById(selectedTabByIndex._id);
  }
}

<div [class]="classNames().headersWrapper">
  @for (headerTemp of tabComponents(); track $index) {
    <ng-container *ngTemplateOutlet="headerTemp._headerTemplate()"></ng-container>
  }
</div>

@let _selectedTabComponent = selectedTabComponent();

@if(!hideContent() && _selectedTabComponent) {
  <div [class]="classNames().contentWrapper">
    <ng-container *ngTemplateOutlet="_selectedTabComponent._contentTemplate()"></ng-container>
  </div>
}

// packages/react/tabs/src/lib/tabs/tabs.tsx
import { Children, CSSProperties, ReactNode, useEffect } from 'react';

import { isNullish } from '@cocokits/common-utils';
import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';
import { useEffectAfterMount } from '@cocokits/react-utils';

import { TabIndexContext, useCreateFeatureStore } from '../tabs.feature-store';
import { TabSelectionChangeEvent } from '../tabs.model';

export interface TabsProps<TValue = unknown> extends UIBaseComponentProps {
  /**
   * The index of the currently selected tab.
   * If `selected` is provided, the value of `selectedIndex` will be ignored.
   * @default 0
   */
  selectedIndex?: number;

  /**
   * The value of the currently selected tab.
   * If not provided, the `selectedIndex` will be used, and if `selectedIndex` is not provided, the first tab will be selected by default.
   */
  selected?: TValue;

  /**
   * Whether to hide the content of the tabs when they are not selected.
   * @default false
   */
  hideContent?: boolean;

  /**
   * Whether to disable the animation when switching between tabs.
   * @default false
   */
  instantAnimation?: boolean;

  /**
   * The alignment of the tab headers.
   * @default 'left'
   */
  headerAlign?: 'left' | 'center' | 'right' | 'stretch';

  /**
   * Callback function that is called when the selected tab changes.
   * The callback receives an object with the new and previous selected index and value.
   */
  onSelectionChange?: (event: TabSelectionChangeEvent<TValue>) => void;
  /**
   * the children of the Tabs component. Must only be `Tab` components.
   */
  children: ReactNode[];
  /**
   * A custom class name that can be used to apply additional styles to the component.
   */
  className?: string;
  /**
   * An object containing inline styles that can be used to customize the appearance of the component.
   */
  style?: CSSProperties;
}

export const Tabs = <TValue,>({
  type,
  size,
  color,
  additional,
  selectedIndex = 0,
  selected,
  hideContent = false,
  instantAnimation = false,
  headerAlign = 'left',
  onSelectionChange,
  children,
  className,
  style,
}: TabsProps<TValue>) => {

  const { store, StoreProvider } = useCreateFeatureStore({
    instantAnimation,
    onSelectionChange: onSelectionChange,
  });
  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'tabs',
    props: { type, size, color, additional },
    extraHostElementClassConditions: [
      { if: !!className, classes: () => [className] },
      { if: headerAlign === 'left', classes: (cn) => [cn.alignLeft] },
      { if: headerAlign === 'right', classes: (cn) => [cn.alignRight] },
      { if: headerAlign === 'center', classes: (cn) => [cn.alignCenter] },
      { if: headerAlign === 'stretch', classes: (cn) => [cn.alignStretch] },
      { if: instantAnimation, classes: (cn) => [cn.instantAnimation] },
    ],
  });

  const selectedTab = store.useSelectedTab();
  const tabComponents = store.useTabComponents();

  // Update config
  useEffectAfterMount(() => {
    store.updateState({
      instantAnimation,
      onSelectionChange,
    });
  }, [instantAnimation, onSelectionChange]);

  // Update selected tab by Index
  useEffect(() => {
    if(!isNullish(selected) || isNullish(selectedIndex)) {
      return;
    }
    store.selectTabByIndex(selectedIndex, false);
  }, [selectedIndex]);

  // Update selected tab by Value
  useEffect(() => {
    if(isNullish(selected)) {
      return;
    }
    store.selectTabByValue(selected, false);
  }, [selected]);

  return (
    <StoreProvider value={store}>
      {/* Just render the children to register them into the store, The Children (Tab Component) will not return any template */}
      {Children.map(children, (child, index) => (
        <TabIndexContext.Provider key={index} value={index}>
          {child}
        </TabIndexContext.Provider>
      ))}

      <div className={hostClassNames} style={style}>
        {/* Labels */}
        <div className={classNames.headersWrapper}>{tabComponents.map((tab) => tab.tabTmp)}</div>

        {/* Content */}
        {/* selectedTab Can be undefined for first render */}
        {!hideContent && selectedTab && (
          <div className={classNames.contentWrapper}>
            {selectedTab.contentTmp}
          </div>
        )}
      </div>
    </StoreProvider>
  );
};

Tabs.displayName = 'Tabs';
export default Tabs;
