// apps/angular-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-box-selection-info/checkbox-box-selection-info.component.ts
import { Component, input } from '@angular/core';

import { CheckboxComponent, SvgIconComponent } from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-box-selection-info.config';

@Component({
  selector: 'cck-checkbox-box-selection-info',
  imports: [CheckboxComponent, SvgIconComponent],
  templateUrl: './checkbox-box-selection-info.component.html',
  styleUrls: ['./checkbox-box-selection-info.component.scss'],
})
export class CheckboxBoxSelectionInfoComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  public readonly Icons = Icons;
}

<div class="checkbox__box">
    <cck-checkbox [value]="1">
        Leave at Door
    </cck-checkbox>
    <cck-svg-icon [icon]='Icons.info' [size]="cckExampleArgs().IconSize" />
</div>
<div class="checkbox__box">
    <cck-checkbox [value]="2">
        Call on Arrival
    </cck-checkbox>
    <cck-svg-icon [icon]='Icons.info' [size]="cckExampleArgs().IconSize" />
</div>

// apps/react-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-box-selection-info/CheckboxBoxSelectionInfo.tsx
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-box-selection-info.config';
import { Checkbox, SvgIcon } from '@cocokits/react-components';

import { Styled } from './CheckboxBoxSelectionInfo.styled';

export function CheckboxBoxSelectionInfo(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <Styled.Container>
      <Styled.Box>
        <Checkbox value={1}>Leave at Door</Checkbox>
        <SvgIcon icon={Icons.info} size={props.cckExampleArgs.IconSize} />
      </Styled.Box>
      <Styled.Box>
        <Checkbox value={2}>Call on Arrival</Checkbox>
        <SvgIcon icon={Icons.info} size={props.cckExampleArgs.IconSize} />
      </Styled.Box>
    </Styled.Container>
  );
}
