// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/input-hint-success/InputHintSuccess.tsx
import { useForm } from 'react-hook-form';

import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/input-hint-success.config';
import { Error,FormField, Hint, Input, Label, SvgIcon } from '@cocokits/react-components';

export function InputHintSuccess(props: { cckExampleArgs: ExampleArgs }) {
  const {
    control,
    formState: { errors, isValid },
  } = useForm<{username: string}>({mode: 'onTouched'});

    
  return (
    <FormField>
      <Label>Username</Label>
      <Input
        name="username"
        control={control}
        rules={{
          required: "Username is required",
          minLength: {
            value: 3,
            message: "Must be at least 3 characters",
          },
          maxLength: {
            value: 10,
            message: "Cannot exceed 10 characters",
          },
          pattern: {
            value: /^[A-Za-z0-9-]+$/,
            message: "Only letters, digits, and hyphens allowed",
          },
        }}
      />
      {
        isValid && (
          <Hint color={props.cckExampleArgs.hintColor}>
            <SvgIcon icon={Icons.checkCircle} />
            <span>Username is available!</span>
          </Hint>
        )
      }
      {
        errors.username && (
          <Error>
            <SvgIcon icon={Icons.warning} />
            <span>{errors.username.message}</span>
          </Error>
        )
      }
    </FormField>
  );
}

// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/input-hint-success/input-hint-success.component.ts
import { Component, input } from '@angular/core';
import { FormControl, ReactiveFormsModule, Validators } from '@angular/forms';

import {
  ErrorComponent,
  FormFieldComponent,
  HintComponent,
  InputComponent,
  LabelComponent,
  ObjToKeysPipe,
  SvgIconComponent,
} from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/input-hint-success.config';

@Component({
  selector: 'cck-input-hint-success',
  imports: [
    FormFieldComponent,
    LabelComponent,
    InputComponent,
    ErrorComponent,
    HintComponent,
    ReactiveFormsModule,
    SvgIconComponent,
    ObjToKeysPipe,
  ],
  template: `
    <cck-form-field>
      <cck-label>Username</cck-label>
      <input cck-input [formControl]="usernameControl" />

      @if (usernameControl.valid) {
        <cck-hint [color]="cckExampleArgs().hintColor">
          <cck-svg-icon [icon]="Icons.checkCircle"></cck-svg-icon>
          <span>Username is available!</span>
        </cck-hint>
      }

      <cck-error>
        <cck-svg-icon [icon]="Icons.warning"></cck-svg-icon>
        <span>{{ errorMessages[(usernameControl.errors | objToKeys)[0]] }}</span>
      </cck-error>
    </cck-form-field>
  `,
  styles: ``,
})
export class InputHintSuccessComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  protected readonly Icons = Icons;
  protected usernameControl = new FormControl('', [
    Validators.required,
    Validators.minLength(3),
    Validators.maxLength(10),
    Validators.pattern(/^[A-Za-z0-9-]+$/),
  ]);

  protected errorMessages = {
    required: 'Username is required',
    minlength: 'Must be at least 3 characters',
    maxlength: 'Cannot exceed 10 characters',
    pattern: 'Only letters, digits, and hyphens allowed',
  };
}
