// apps/angular-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-label-link/checkbox-label-link.component.ts
import { Component, input } from '@angular/core';

import { CheckboxComponent } from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-label-link.config';

@Component({
  selector: 'cck-checkbox-label-link',
  imports: [CheckboxComponent],
  template: `
    <cck-checkbox
      >I accept the
      <a href="https://cocokits.com" target="_blank" rel="noopener noreferrer">Privacy Policy</a></cck-checkbox
    >
  `,
  styles: ``,
})
export class CheckboxLabelLinkComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}

// apps/react-kits-doc/stories/ui-components/checkbox/checkbox/examples/checkbox-label-link/CheckboxLabelLink.tsx
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/checkbox/checkbox-label-link.config';
import { Checkbox } from '@cocokits/react-components';

export function CheckboxLabelLink(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <Checkbox value={1}>
      I accept the
      <a href="https://cocokits.com" target="_blank" rel="noopener noreferrer">
        Privacy Policy
      </a>
    </Checkbox>
  );
}
