// packages/angular/accordion/src/lib/accordion-header/accordion-header.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChild,
  inject,
  TemplateRef,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';
import { SvgIconComponent } from '@cocokits/angular-icon';

import { AccordionStore } from '../accordion.store';
import { AccordionComponent } from '../accordion/accordion.component';
import { AccordionHeaderIconTemplateDirective } from '../accordion-header-icon.tmpl-directive';
import { AccordionPanelComponent } from '../accordion-panel/accordion-panel.component';

@Component({
  imports: [SvgIconComponent, CommonModule],
  selector: 'cck-accordion-header',
  templateUrl: './accordion-header.component.html',
  styleUrls: ['./accordion-header.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
    '(click)': 'onHostClick()',
  },
})
export class AccordionHeaderComponent extends _UiBaseComponent<'accordionHeader'> {
  protected readonly componentName = 'accordionHeader';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.accordionRef.iconPosition() === 'left', classes: this.classNames().iconLeft },
    { if: this.accordionRef.iconPosition() === 'right', classes: this.classNames().iconRight },
    { if: this.accordionRef.toggleTrigger() === 'icon', classes: this.classNames().triggerIcon },
    { if: this.accordionRef.toggleTrigger() === 'header', classes: this.classNames().triggerHeader },
  ]);

  protected accordionRef = inject(AccordionComponent);
  protected panelRef = inject(AccordionPanelComponent);
  protected store = inject(AccordionStore);

  protected expandedIcon: string;
  protected collapsedIcon: string;

  protected readonly isExpanded = this.store.isExpanded(this.panelRef._id);

  private customIconTemp = contentChild(AccordionHeaderIconTemplateDirective, { read: TemplateRef<HTMLElement> });
  private defaultIconTemp = viewChild.required<TemplateRef<HTMLElement>>('defaultIconTemp');

  protected template = computed(
    () => this.customIconTemp() ?? this.accordionRef._customIconTemp() ?? this.defaultIconTemp()
  );

  constructor() {
    super();

    const expandedIcon = this.themeConfig.components.accordion?.templates?.accordionExpandedIcon;
    const collapsedIcon = this.themeConfig.components.accordion?.templates?.accordionCollapsedIcon;
    if (!expandedIcon) {
      throw new Error('`accordionExpandedIcon` has not defined in `ThemeConfig` of selected theme');
    }
    if (!collapsedIcon) {
      throw new Error('`accordionCollapsedIcon` has not defined in `ThemeConfig` of selected theme');
    }

    this.expandedIcon = expandedIcon;
    this.collapsedIcon = collapsedIcon;
  }

  protected onHostClick() {
    if (this.panelRef.disabled() || this.accordionRef.toggleTrigger() !== 'header') {
      return;
    }
    this.store.toggle(this.panelRef._id);
  }

  protected toggle() {
    if (this.panelRef.disabled() || this.accordionRef.toggleTrigger() !== 'icon') {
      return;
    }
    this.store.toggle(this.panelRef._id);
  }
}

<ng-content></ng-content>

<div [class]="classNames().iconWrapper" (click)="toggle()">
  <ng-container *ngTemplateOutlet="template(); context: { 
      isExpanded: isExpanded(), 
      disabled: panelRef.disabled() 
    }"></ng-container>
</div>

<ng-template #defaultIconTemp let-isExpanded="isExpanded">
  <button cck-icon-button>
    @if(isExpanded) {
      <cck-svg-icon [icon]="expandedIcon"/>
    } @else {
      <cck-svg-icon [icon]="collapsedIcon"/>
    }
  </button>
</ng-template>

// packages/react/accordion/src/lib/accordion-header/accordion-header.tsx
/* eslint-disable max-lines-per-function */
import React, { useCallback, useContext } from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { ThemeConfigContext, useUiBaseComponentConfig } from '@cocokits/react-core';
import { SvgIcon } from '@cocokits/react-icon';

import { useAccordionStore } from '../accordion.store';
import { AccordionPanelContext } from '../accordion-panel/accordion-panel';

export interface AccordionHeaderProps extends UIBaseComponentProps {
  iconTemplate?:
    | React.ReactNode
    | React.ReactNode[]
    | ((props: { isExpanded: boolean; disabled: boolean }) => React.ReactNode);
  children?: React.ReactNode;
}

export const AccordionHeader = ({ type, size, color, additional, iconTemplate, children }: AccordionHeaderProps) => {
  const store = useAccordionStore();
  const panelContext = useContext(AccordionPanelContext);
  const themeConfig = useContext(ThemeConfigContext);

  const expandedIcon = themeConfig?.components.accordion?.templates?.accordionExpandedIcon;
  const collapsedIcon = themeConfig?.components.accordion?.templates?.accordionCollapsedIcon;

  if(!store) {
    throw new Error('AccordionHeader must be used within an Accordion.');
  }
  if (!panelContext) {
    throw new Error('AccordionHeader must be used within an AccordionPanel.');
  }

  const isExpanded = store?.isExpanded(panelContext.id);
  const iconPosition = store.useState((state) => state.iconPosition);
  const toggleTrigger = store.useState((state) => state.toggleTrigger);

  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'accordionHeader',
    props: { type, size, color, additional },
    extraHostElementClassConditions: [
      { if: iconPosition === 'left', classes: (cn) => [cn.iconLeft] },
      { if: iconPosition === 'right', classes: (cn) => [cn.iconRight] },
      { if: toggleTrigger === 'icon', classes: (cn) => [cn.triggerIcon] },
      { if: toggleTrigger === 'header', classes: (cn) => [cn.triggerHeader] },
    ],
  });

  const onHostClick = () => {
    if (panelContext.disabled || store?.getState().toggleTrigger !== 'header') {
      return;
    }

    store?.toggle(panelContext.id);
  };

  const toggle = () => {
    if (panelContext.disabled || store?.getState().toggleTrigger !== 'icon') {
      return;
    }

    store?.toggle(panelContext.id);
  };

  const iconContent = useCallback(() => {
    if (typeof iconTemplate === 'function') {
      return iconTemplate({ isExpanded: isExpanded ?? false, disabled: panelContext.disabled ?? false });
    }

    if(iconTemplate) {
      return iconTemplate as React.ReactNode;
    }

    const globalIconTemplate = store.getState().iconTemplate;

    if (typeof globalIconTemplate === 'function') {
      return globalIconTemplate({ isExpanded: isExpanded ?? false, disabled: panelContext.disabled ?? false });
    }

    if(globalIconTemplate) {
      return globalIconTemplate as React.ReactNode;
    }

    if(!expandedIcon || !collapsedIcon) {
      throw new Error('`expandedIcon` and `collapsedIcon` must be defined in the theme configuration.');
    }

    return (
      <SvgIcon icon={isExpanded ? expandedIcon : collapsedIcon}></SvgIcon>
    );
  }, [iconTemplate, isExpanded, panelContext.disabled]);

  return (
    <div className={hostClassNames} onClick={onHostClick}>
      {children}
      <button className={classNames.iconBtn} onClick={toggle}>
        {iconContent()}
      </button>
    </div>
  );
};

AccordionHeader.displayName = 'AccordionHeader';
export default AccordionHeader;
