// packages/react/form-field/src/lib/select-store.ts
import { Selection, SelectionOptions } from '@cocokits/common-utils';
import { createComponentStore } from '@cocokits/react-utils';
import { createContext, useContext, useMemo, Provider } from 'react';

interface SelectState<T> {
  selectedItems: T[] | undefined;
  isEmpty: boolean;
  hasValue: boolean;
  // isMultiple: boolean;
}

export interface SelectStoreConfig<T> {
  onSelectionChange?: (selected: T[]) => void;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const DEFAULT_STATE: SelectState<any> = {
  selectedItems: undefined,
  isEmpty: true,
  hasValue: false,
  // isMultiple: false,
};

class SelectStore<T> {
  private selection = new Selection<T>();
  private state = createComponentStore<SelectState<T>>(DEFAULT_STATE);
  private onSelectionChange?: (selected: T[]) => void;

  constructor({ onSelectionChange }: SelectStoreConfig<T> = {}) {
    this.onSelectionChange = onSelectionChange;
    this.selection.addChangeEventListener(() => {
      this.syncSelectionWithStore();
      this.onSelectionChange?.(this.selection.getSelected());
    });
  }

  public useState = this.state.useState;
  public getState = this.state.getState;

  public clear = () => this.selection.clear();
  public deselect = (values: T | T[]) => this.selection.deselect(values);
  public setSelection = (values: T | T[]) => this.selection.setSelection(values);
  public toggle = (value: T) => this.selection.toggle(value);
  public select = (values: T | T[], skipEmitEvent = false) => {
    this.selection.select(values, { skipEmitEvent });
    if (skipEmitEvent) {
      this.syncSelectionWithStore();
    }
  };

  private syncSelectionWithStore() {
    this.state.updateState({
      selectedItems: this.selection.getSelected(),
      isEmpty: this.selection.isEmpty(),
      hasValue: this.selection.hasValue(),
      // isMultiple: this.selection.isMultipleSelection(),
    });
  }

  public resetWithOption(options: Partial<SelectionOptions<T>> = {}) {
    this.selection.clear();
    this.selection.updateOptions(options);
    this.syncSelectionWithStore();
  }

  public useIsSelected(item: T) {
    return this.state.useState((state) => state.selectedItems?.includes(item) ?? false);
  }

  public destroy() {
    this.selection.removeAllChangeEventListener();
  }
}

const SelectStoreContent = createContext<SelectStore<unknown> | null>(null);

export function useCreateSelectStore<T>(config?: SelectStoreConfig<T>) {
  return useMemo(
    () => ({
      SelectStoreProvider: SelectStoreContent.Provider as Provider<SelectStore<T>>,
      selectStore: new SelectStore<T>(config),
    }),
    []
  );
}

export function useSelectStore<T>() {
  return useContext(SelectStoreContent) as SelectStore<T> | null;
}

// packages/angular/form-field/src/lib/select.store.ts
import { inject, Injectable, InjectionToken, OnDestroy, Signal, signal, WritableSignal } from '@angular/core';

import { Subject } from 'rxjs';

// eslint-disable-next-line @nx/enforce-module-boundaries
import { RenderedOverlay } from '@cocokits/angular-overlay';
import { Selection, SelectionOptions, SelectionUpdateConfig } from '@cocokits/common-utils';

export enum SelectTriggerSource {
  FromControl = 'fromControl',
  FromOption = 'fromOption',
}

export const SelectStore = new InjectionToken<SelectStoreService<any>>('SELECT_STORE_SERVICE');

export function injectSelectStore<T>(): SelectStoreService<T> {
  return inject(SelectStore, { optional: true }) ?? new SelectStoreService<T>();
}

@Injectable()
export class SelectStoreService<T> implements OnDestroy {
  private selection = new Selection<T>();
  private selectionSignalMap = new Map<T, WritableSignal<boolean>>();
  public renderedOverlay: RenderedOverlay<void, T> | undefined;

  private changesSubject$ = new Subject<{ selected: T[]; triggerSource: SelectTriggerSource }>();
  public changes$ = this.changesSubject$.asObservable();

  // region ---------------- selectedItems ----------------
  private _selectedItems: WritableSignal<T[]> | undefined;
  public get selectedItems(): Signal<T[]> {
    if (!this._selectedItems) {
      this._selectedItems = signal(this.selection.getSelected());
    }

    return this._selectedItems.asReadonly();
  }
  private set selectedItems(items: T[]) {
    this._selectedItems?.set(items);
  }
  // endregion

  // region ---------------- isEmpty ----------------
  private _isEmpty: WritableSignal<boolean> | undefined;
  public get isEmpty(): Signal<boolean> {
    if (!this._isEmpty) {
      this._isEmpty = signal(this.selection.isEmpty());
    }

    return this._isEmpty.asReadonly();
  }
  private set isEmpty(isEmpty: boolean) {
    this._isEmpty?.set(isEmpty);
  }
  // endregion

  // region ---------------- hasValue ----------------
  private _hasValue: WritableSignal<boolean> | undefined;
  public get hasValue(): Signal<boolean> {
    if (!this._hasValue) {
      this._hasValue = signal(this.selection.hasValue());
    }

    return this._hasValue.asReadonly();
  }
  private set hasValue(hasValue: boolean) {
    this._hasValue?.set(hasValue);
  }
  // endregion

  // region ---------------- hasValue ----------------
  private _isMultiple: WritableSignal<boolean> | undefined;
  public get isMultiple(): Signal<boolean> {
    if (!this._isMultiple) {
      this._isMultiple = signal(this.selection.isMultipleSelection());
    }

    return this._isMultiple.asReadonly();
  }
  private set isMultiple(isMultiple: boolean) {
    this._isMultiple?.set(isMultiple);
  }

  constructor() {
    this.selection.addChangeEventListener((changes) => {
      changes.added.forEach((item) => {
        const itemSignal = this.selectionSignalMap.get(item);
        itemSignal?.set(true);
      });

      changes.removed.forEach((item) => {
        const itemSignal = this.selectionSignalMap.get(item);
        itemSignal?.set(false);
      });

      this.changesSubject$.next({
        selected: this.selection.getSelected(),
        triggerSource: changes.triggerSource as SelectTriggerSource,
      });

      this.syncValuesWithSelection();
    });
  }

  private syncValuesWithSelection() {
    this.selectedItems = this.selection.getSelected();
    this.isEmpty = this.selection.isEmpty();
    this.hasValue = this.selection.hasValue();
  }

  public resetWithOption(options: Partial<SelectionOptions<T>> = {}) {
    this.selection.clear();
    this.selection.updateOptions(options);
    this.isMultiple = this.selection.isMultipleSelection();
    this.syncValuesWithSelection();
  }

  public isSelected(item: T): Signal<boolean> {
    const itemSignal = this.selectionSignalMap.get(item);

    if (itemSignal) {
      return itemSignal.asReadonly();
    }

    const newSignal = signal(this.selection.isSelected(item));
    this.selectionSignalMap.set(item, newSignal);
    return newSignal.asReadonly();
  }

  public clear(config?: SelectionUpdateConfig) {
    this.selection.clear(config);
  }

  public select(items: T | T[], config?: SelectionUpdateConfig) {
    this.selection.select(items, config);
  }

  public deselect(items: T | T[], config?: SelectionUpdateConfig) {
    this.selection.deselect(items, config);
  }

  public setSelection(items: T | T[], config?: SelectionUpdateConfig) {
    this.selection.setSelection(items, config);
  }

  public toggle(items: T, config?: SelectionUpdateConfig) {
    this.selection.toggle(items, config);
  }

  ngOnDestroy() {
    this.selection.removeAllChangeEventListener();
    this.selectionSignalMap.clear();
  }
}
