// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/phone-number/PhoneNumber.tsx
import InputMask from '@mona-health/react-input-mask';
import { useState } from 'react';

import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/phone-number.config';
import { FormField, Hint, Input, Label, Option, Select, Suffix, SvgIcon } from '@cocokits/react-components';

import { ATFlag, THFlag } from './flags';
import { Styled } from './PhoneNumber.styled';

const FlagsMap = {
  TH: THFlag,
  AT: ATFlag,
};

export function PhoneNumber(props: { cckExampleArgs: ExampleArgs }) {
  const [value, setValue] = useState<'TH' | 'AT'>('TH');

  return (
    <FormField>
      <Label>Phone number</Label>
      <Styled.Prefix>+{value === 'TH' ? '66' : '43'}</Styled.Prefix>
      <InputMask mask={value === 'TH' ? '999-999-999' : '999 9999 999'} maskPlaceholder={null}>
        <Input />
      </InputMask>
      <Suffix>
        <Select
          value={value}
          onChange={(e) => setValue(e[0] as 'TH' | 'AT')}
          selectPreview={(selected) => (
            <SvgIcon size={props.cckExampleArgs.previewFlagSize} icon={FlagsMap[selected[0]]} />
          )}>
          <Option value="TH">
            <Styled.OptionWrapper>
              <SvgIcon size={props.cckExampleArgs.optionFlagSize} icon={THFlag} />
              TH
            </Styled.OptionWrapper>
          </Option>
          <Option value="AT">
            <Styled.OptionWrapper>
              <SvgIcon size={props.cckExampleArgs.optionFlagSize} icon={ATFlag} />
              AT
            </Styled.OptionWrapper>
          </Option>
        </Select>
      </Suffix>
      <Hint>Enter your local phone number</Hint>
    </FormField>
  );
}

// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/phone-number/phone-number.component.ts
import { Component, input, signal } from '@angular/core';

import { NgxMaskDirective, provideNgxMask } from 'ngx-mask';

import {
  FormFieldComponent,
  HintComponent,
  InputComponent,
  LabelComponent,
  OptionComponent,
  PrefixComponent,
  SelectComponent,
  SelectPreviewComponent,
  SuffixComponent,
  SvgIconComponent,
} from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/phone-number.config';

import { ATFlag, THFlag } from './flags';

@Component({
  standalone: true,
  selector: 'cck-phone-number',
  imports: [
    FormFieldComponent,
    LabelComponent,
    PrefixComponent,
    InputComponent,
    SelectComponent,
    OptionComponent,
    HintComponent,
    NgxMaskDirective,
    SuffixComponent,
    SvgIconComponent,
    SelectPreviewComponent,
  ],
  providers: [provideNgxMask()],
  templateUrl: './phone-number.component.html',
  styleUrls: ['./phone-number.component.scss'],
})
export class PhoneNumberComponent {
  public cckExampleArgs = input.required<ExampleArgs>();

  protected value = signal<'TH' | 'AT'>('TH');

  protected THFlag = THFlag;
  protected ATFlag = ATFlag;
}

<cck-form-field>
  <cck-label>Phone number</cck-label>
  <cck-prefix class="prefix">+{{ value() === 'TH' ? '66' : '43' }}</cck-prefix>
  <input cckInput [mask]="value() === 'TH' ? '999-999-999' : '999 9999 999'">
  <cck-suffix>
    <cck-select
      [value]="value()"
      (selectionChange)="value.set($event[0])">

      <cck-select-preview>
        <cck-svg-icon [size]="cckExampleArgs().previewFlagSize" [icon]="value() === 'TH' ? THFlag : ATFlag"></cck-svg-icon>
      </cck-select-preview>

      <cck-option value="TH">
        <div class="option-wrapper">
          <cck-svg-icon [size]="cckExampleArgs().optionFlagSize" [icon]="THFlag"></cck-svg-icon>
          TH
        </div>
      </cck-option>
      <cck-option value="AT">
        <div class="option-wrapper">
          <cck-svg-icon [size]="cckExampleArgs().optionFlagSize" [icon]="ATFlag"></cck-svg-icon>
          AT
        </div>
      </cck-option>
    </cck-select>
  </cck-suffix>
  <cck-hint>Enter your local phone number</cck-hint>
</cck-form-field>
