// packages/react/form-field/src/lib/form-field.tsx
'use client';
import { CSSProperties, Fragment, ReactNode, useEffect, useRef } from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';

import { useCreateFormStore } from './form-store';

export interface FormFieldProps extends UIBaseComponentProps {
  /**
   * Whether the form field is disabled.
   */
  disabled?: boolean;
  /**
   * Whether the field is required.
   */
  required?: boolean;
  /**
   * Whether the form field is invalid.
   */
  invalid?: boolean;
  /**
   * Whether the required marker should be hidden.
   */
  hideRequiredMarker?: boolean | undefined;
  /**
   * The content inside the component.
   * This can be a string, a number, an element, or an array of elements.
   * It allows rendering nested components within this component.
   */
  children?: ReactNode | ReactNode[];
  /**
   * A custom class name that can be used to apply additional styles to the component.
   */
  className?: string;
  /**
   * An object containing inline styles that can be used to customize the appearance of the component.
   */
  style?: CSSProperties;
}

export const FormField = (props: FormFieldProps) => {
  const { formStore, FormStoreProvider } = useCreateFormStore();

  const disabled = formStore.useState((state) => state.disabled);
  const required = formStore.useState((state) => state.required);
  const focused = formStore.useState((state) => state.focused);
  const hasInput = formStore.useState((state) => state.hasInput);
  const hasSelect = formStore.useState((state) => state.hasSelect);
  const hasChipList = formStore.useState((state) => state.hasChipList);
  const hasTextarea = formStore.useState((state) => state.hasTextarea);
  const invalid = formStore.useState((state) => state.invalid);
  const error = formStore.useState((state) => state.error);
  const size = formStore.useState((state) => state.size);
  const labelTemplate = formStore.useState((state) => state.labelTemplate);
  const hintTemplate = formStore.useState((state) => state.hintTemplate);
  const errorsTemplates = formStore.useState((state) => state.errorsTemplates);
  const prefixTemplate = formStore.useState((state) => state.prefixTemplate);
  const suffixTemplate = formStore.useState((state) => state.suffixTemplate);
  const leadingTemplate = formStore.useState((state) => state.leadingTemplate);
  const trailingTemplate = formStore.useState((state) => state.trailingTemplate);

  const wrapperElemRef = useRef<HTMLDivElement>(null);

  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'formField',
    props: { ...props, size },
    extraHostElementClassConditions: [
      { if: disabled, classes: (cn) => [cn.disabled] },
      { if: required, classes: (cn) => [cn.required] },
      { if: focused, classes: (cn) => [cn.focused] },
      { if: hasInput, classes: (cn) => [cn.withInput] },
      { if: hasSelect, classes: (cn) => [cn.withSelect] },
      { if: hasChipList, classes: (cn) => [cn.withChipList] },
      { if: hasTextarea, classes: (cn) => [cn.withTextarea] },
      { if: invalid, classes: (cn) => [cn.invalid] },
      { if: error, classes: (cn) => [cn.error] },
      { if: !!props.className, classes: () => [props.className] },
      // TODO: add formControl like react-hook-form. with untouched, touched, pristine, dirty, valid, invalid, pending
    ],
  });

  useEffect(() => {
    formStore.registerComponent('formField');
    return () => formStore.unregisterComponent('formField');
  }, [formStore]);

  useEffect(() => {
    formStore.deepUpdateComponent('formField', {
      wrapperElem: wrapperElemRef.current,
      disabled: props.disabled,
      required: props.required,
      invalid: props.invalid,
      size: props.size,
      hideRequiredMarker: props.hideRequiredMarker,
    });
  }, [
    wrapperElemRef.current,
    formStore,
    props.disabled,
    props.required,
    props.invalid,
    props.size,
    props.hideRequiredMarker,
  ]);

  return (
    <FormStoreProvider value={formStore}>
      <div style={props.style} className={hostClassNames}>
        {labelTemplate}

        <div className={classNames.wrapper} ref={wrapperElemRef}>
          {leadingTemplate}
          <div className={classNames.inputWrapper}>
            {prefixTemplate}
            {props.children}
            {suffixTemplate}
          </div>
          {trailingTemplate}
        </div>

        <div className={classNames.feedbackWrapper}>
          {hintTemplate}
          {errorsTemplates.map((errorTemplate, index) => {
            return <Fragment key={index}>{errorTemplate}</Fragment>;
          })}
        </div>
      </div>
    </FormStoreProvider>
  );
};

FormField.displayName = 'FormField';
export default FormField;

// packages/angular/form-field/src/lib/form-field/form-field.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  OnDestroy,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';

import { FormFieldStore, FormFieldStoreService, injectFormFieldStore } from '../form-field.store';
import { toBooleanOrPresent } from '@cocokits/common-utils';

@Component({
  standalone: true,
  imports: [],
  selector: 'cck-form-field',
  templateUrl: './form-field.component.html',
  styleUrls: ['./form-field.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    {
      provide: FormFieldStore,
      useClass: FormFieldStoreService,
    },
  ],
  host: {
    '[class]': 'hostClassNames()',
  },
})
export class FormFieldComponent extends _UiBaseComponent<'formField'> implements OnDestroy {
  protected readonly componentName = 'formField';
  protected store = injectFormFieldStore();
  private cd = inject(ChangeDetectorRef);

  /**
   * Whether the required marker should be hidden.
   */
  public hideRequiredMarker = input<boolean>();

  /**
   * Whether the control is disabled.
   */
  public disabled = input(null, { transform: toBooleanOrPresent });

  protected extraHostElementClassConditions = computed(() => [
    { if: this.store.state.disabled(), classes: this.classNames().disabled },
    { if: this.store.state.focused(), classes: this.classNames().focused },
    { if: this.store.state.hasError(), classes: this.classNames().error },
    { if: this.store.state.hasInput(), classes: this.classNames().withInput },
    { if: this.store.state.hasTextarea(), classes: this.classNames().withTextarea },
    { if: this.store.state.hasSelect(), classes: this.classNames().withSelect },
    { if: this.store.state.hasChipList(), classes: this.classNames().withChipList },
    { if: this.store.control.untouched(), classes: this.classNames().untouched },
    { if: this.store.control.touched(), classes: this.classNames().touched },
    { if: this.store.control.pristine(), classes: this.classNames().pristine },
    { if: this.store.control.dirty(), classes: this.classNames().dirty },
    { if: this.store.control.valid(), classes: this.classNames().valid },
    { if: this.store.control.invalid(), classes: this.classNames().invalid },
    { if: this.store.control.pending(), classes: this.classNames().pending },
  ]);

  public wrapperElemRef = viewChild.required<ElementRef<HTMLElement>>('wrapperElem');

  constructor() {
    super();
    this.store.registerComponent('formField', this, this.cd);
  }

  ngOnDestroy() {
    this.store.unregisterComponent(this, this.cd);
  }
}

<ng-content select='cck-label'></ng-content>

<div #wrapperElem [class]="classNames().wrapper">

  <ng-content select='cck-leading'></ng-content>

  <div [class]="classNames().inputWrapper">
    <ng-content select='cck-prefix'></ng-content>
    <ng-content></ng-content>
    <ng-content select='cck-suffix'></ng-content>
  </div>

  <ng-content select='cck-trailing'></ng-content>
</div>

<div class="cck-form-field__feedback-wrapper">
  <ng-content select='cck-hint'></ng-content>
  <ng-content select='cck-error'></ng-content>
</div>
