// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/trailing-copy/trailing-copy.component.ts
import { Component, input, signal } from '@angular/core';

import {
  FormFieldComponent,
  HintComponent,
  InputComponent,
  LabelComponent,
  SvgIconComponent,
  TrailingComponent,
} from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/trailing-copy.config';

@Component({
  selector: 'cck-trailing-copy',
  imports: [FormFieldComponent, InputComponent, TrailingComponent, LabelComponent, SvgIconComponent, HintComponent],
  template: `
    <cck-form-field>
      <cck-label>Copy text</cck-label>
      <input value="cocokits.com" cck-input />
      <cck-trailing [clickable]="true" (click)="onCopyClick()">
        <cck-svg-icon [icon]="Icons.copy" />
      </cck-trailing>

      @if (showHint()) {
        <cck-hint>Copied</cck-hint>
      }
    </cck-form-field>
  `,
  styles: ``,
})
export class TrailingCopyComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  public Icons = Icons;

  private setTimeoutId!: NodeJS.Timeout;
  protected showHint = signal(false);

  onCopyClick() {
    clearTimeout(this.setTimeoutId);
    this.showHint.set(true);

    this.setTimeoutId = setTimeout(() => {
      this.showHint.set(false);
    }, 3000);
  }
}

// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/trailing-copy/TrailingCopy.tsx
import { useEffect, useState } from 'react';

import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/trailing-copy.config';
import { FormField, Hint, Input, Label, SvgIcon, Trailing } from '@cocokits/react-components';

export function TrailingCopy(props: { cckExampleArgs: ExampleArgs }) {
  const [showHint, setShowHint] = useState(false);

  useEffect(() => {
    let setTimeoutId: NodeJS.Timeout;
    if (showHint) {
      setTimeoutId = setTimeout(() => {
        setShowHint(false);
      }, 3000);
    }

    return () => {
      clearTimeout(setTimeoutId);
    };
  }, [showHint]);

  return (
    <FormField>
      <Label>Copy text</Label>
      <Input defaultValue="cocokits.com"></Input>
      <Trailing clickable={true} onClick={() => setShowHint(true)}>
        <SvgIcon icon={Icons.copy} />
      </Trailing>
      {showHint && <Hint>Copied</Hint>}
    </FormField>
  );
}
