// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/trailing-domain/TrailingDomain.tsx
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/trailing-domain.config';
import { FormField, Input, Label, Trailing } from '@cocokits/react-components';

export function TrailingDomain(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <FormField>
      <Label>Choose domain name</Label>
      <Input />
      <Trailing>.com</Trailing>
    </FormField>
  );
}

// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/trailing-domain/trailing-domain.component.ts
import { Component, input } from '@angular/core';

import { FormFieldComponent, InputComponent, LabelComponent, TrailingComponent } from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/trailing-domain.config';

@Component({
  selector: 'cck-trailing-domain',
  imports: [FormFieldComponent, InputComponent, TrailingComponent, LabelComponent],
  template: `
    <cck-form-field>
      <cck-label>Choose domain name</cck-label>
      <cck-trailing>.com</cck-trailing>
      <input cck-input />
    </cck-form-field>
  `,
  styles: ``,
})
export class TrailingDomainComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
}
