// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/textarea-max-char/TextareaMaxChar.tsx
import { useState } from 'react';

import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/textarea-max-char.config';
import { FormField, Hint, Label, Textarea } from '@cocokits/react-form-field';

export function TextareaMaxChar(props: { cckExampleArgs: ExampleArgs }) {
  const [valueLength, setValueLength] = useState(0);
  const maxLength = 150;

  return (
    <FormField>
      <Label>Description</Label>
      <Textarea 
        maxLength={maxLength}
        placeholder="Short project description"
        onChange={e => setValueLength(e.target.value.length)}/>
      <Hint>{valueLength}/{maxLength} characters max</Hint>
    </FormField>
  );
}

// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/textarea-max-char/textarea-max-char.component.ts
import { Component, input, signal } from '@angular/core';

import { FormFieldComponent, HintComponent, LabelComponent, TextareaComponent } from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/textarea-max-char.config';

@Component({
  selector: 'cck-textarea-max-char',
  imports: [FormFieldComponent, TextareaComponent, LabelComponent, HintComponent],
  template: `
    <cck-form-field>
      <cck-label>Description</cck-label>
      <textarea
        cck-textarea
        [maxLength]="maxLength"
        placeholder="Short project description"
        (input)="onChange($event)"></textarea>
      <cck-hint>{{ valueLength() }}/{{ maxLength }} characters max</cck-hint>
    </cck-form-field>
  `,
  styles: ``,
})
export class TextareaMaxCharComponent {
  public cckExampleArgs = input.required<ExampleArgs>();

  protected readonly maxLength = 10;
  protected valueLength = signal(0);

  protected onChange(e: Event) {
    const textareaElem = e.target as HTMLTextAreaElement;
    this.valueLength.set(textareaElem.value.length);
  }
}
