// packages/angular/avatar/src/lib/avatar-label/avatar-label.component.ts
import { ChangeDetectionStrategy, Component, computed, input, ViewEncapsulation } from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';

@Component({
  imports: [],
  selector: 'cck-avatar-label',
  templateUrl: './avatar-label.component.html',
  styleUrls: ['./avatar-label.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'hostClassNames()',
  },
})
export class AvatarLabelComponent extends _UiBaseComponent<'avatarLabel'> {
  protected readonly componentName = 'avatarLabel';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.avatarPosition() === 'left', classes: this.classNames().avatarPositionLeft },
    { if: this.avatarPosition() === 'right', classes: this.classNames().avatarPositionRight },
    { if: this.avatarPosition() === 'top', classes: this.classNames().avatarPositionTop },
    { if: this.avatarPosition() === 'bottom', classes: this.classNames().avatarPositionBottom },
    { if: this.labelAlignment() === 'horizontal', classes: this.classNames().labelAlignmentHorizontal },
    { if: this.labelAlignment() === 'vertical', classes: this.classNames().labelAlignmentVertical },
  ]);

  /**
   * The position of the avatar relative to the label.
   */
  public avatarPosition = input<'left' | 'right' | 'top' | 'bottom'>('left');

  /**
   * The alignment of the label
   */
  public labelAlignment = input<'horizontal' | 'vertical'>('vertical');

  /**
   * The title text of component.
   */
  public title = input<string>();

  /**
   * The description text of avatar
   */
  public description = input<string>();
}

<ng-content selector="cck-avatar"/>
<div [class]="classNames().labelWrapper">
  <span [class]="classNames().title">{{ title() }}</span>
  <span [class]="classNames().description">{{ description() }}</span>
</div>

// packages/react/avatar/src/lib/avatar-label/avatar-label.tsx
import React from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';

export type AvatarLabelContextValue = UIBaseComponentProps;
export const AvatarLabelContext = React.createContext<AvatarLabelContextValue | null>(null);

export interface AvatarLabelProps extends UIBaseComponentProps {
  /**
   * The position of the avatar relative to the label.
   * @defaultValue 'left'
   */
  avatarPosition?: 'left' | 'right' | 'top' | 'bottom';

  /**
   * The alignment of the label
   * @defaultValue 'vertical'
   */
  labelAlignment?: 'horizontal' | 'vertical';

  /**
   * The title text of avatar.
   */
  title?: string;

  /**
   * The description text of avatar.
   */
  description?: string;

  /**
   * The children should contain the avatar component
   */
  children?: React.ReactNode;
}

export const AvatarLabel = ({ type, size, color, additional, children, avatarPosition = 'left', labelAlignment = 'vertical', ...restProps }: AvatarLabelProps) => {
  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'avatarLabel',
    props: { type, size, color, additional },
    extraHostElementClassConditions: [
      { if: avatarPosition === 'left', classes: (cn) => [cn.avatarPositionLeft] },
      { if: avatarPosition === 'right', classes: (cn) => [cn.avatarPositionRight] },
      { if: avatarPosition === 'top', classes: (cn) => [cn.avatarPositionTop] },
      { if: avatarPosition === 'bottom', classes: (cn) => [cn.avatarPositionBottom] },
      { if: labelAlignment === 'horizontal', classes: (cn) => [cn.labelAlignmentHorizontal] },
      { if: labelAlignment === 'vertical', classes: (cn) => [cn.labelAlignmentVertical] }
    ]
  });

  return (
    <AvatarLabelContext.Provider value={{ type, size, color, additional }}>
      <div className={hostClassNames}>
        {children}
        <div className={classNames.labelWrapper}>
          {restProps.title && <div className={classNames.title}>{restProps.title}</div>}
          {restProps.description && <div className={classNames.description}>{restProps.description}</div>}
        </div>
      </div>
    </AvatarLabelContext.Provider>
  );
};

AvatarLabel.displayName = 'AvatarLabel';
export default AvatarLabel;
