// apps/angular-kits-doc/stories/ui-components/button/button/examples/show-more-button/show-more-button.component.ts
import { Component, input } from '@angular/core';

import { ButtonComponent, SvgIconComponent } from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/show-more-button.config';

@Component({
  selector: 'cck-show-more-button',
  imports: [ButtonComponent, SvgIconComponent],
  template: `
    <button cck-button [type]="cckExampleArgs().buttonType" [color]="cckExampleArgs().buttonColor">
      <span>Show More</span>
      <cck-svg-icon [icon]="Icons.arrowHeadDown"></cck-svg-icon>
    </button>
  `,
  styles: ``,
})
export class ShowMoreButtonComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  public readonly Icons = Icons;
}

// apps/react-kits-doc/stories/ui-components/button/button/examples/show-more-button/ShowMoreButton.tsx
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/show-more-button.config';
import { Button, SvgIcon } from '@cocokits/react-components';

export function ShowMoreButton(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <Button type={props.cckExampleArgs.buttonType} color={props.cckExampleArgs.buttonColor}>
      <span>Show More</span>
      <SvgIcon icon={Icons.arrowHeadDown} />
    </Button>
  );
}
