// packages/react/tabs/src/lib/tab/tab.tsx
import { CSSProperties, ReactNode, useContext, useLayoutEffect, useRef } from 'react';

import { UIBaseComponentProps } from '@cocokits/core';
import { useUiBaseComponentConfig } from '@cocokits/react-core';
import { useOnDestroy, useStaticText } from '@cocokits/react-utils';

import { TabIndexContext, useFeatureStore } from '../tabs.feature-store';

export interface TabProps<TValue = unknown> extends UIBaseComponentProps {

  /**
   * The label of the tab, which can be a string or a function that receives a boolean indicating if the tab is selected.
   * If a function is provided, it should return a ReactNode to be rendered as the label.
   */
  header: string | ((selected: boolean) => ReactNode);

  /**
   * The value of the tab, which is used to identify the tab when selected.
   * If not provided, a unique ID will be used.
   */
  value?: TValue;

  /**
   * Whether the tab is disabled. If true, the tab will not be selectable by user.
   * @default false
   */
  disabled?: boolean;

  /**
   * The content of tab component.
   */
  children?: ReactNode | ReactNode[];

  /**
   * A custom class name that can be used to apply additional styles to the component.
   */
  className?: string;

  /**
   * An object containing inline styles that can be used to customize the appearance of the component.
   */
  style?: CSSProperties;
}

export const Tab = <TValue,>({
  type,
  size,
  color,
  additional,
  header,
  value,
  disabled = false,
  children,
  className,
  style,
}: TabProps<TValue>) => {
  const id = useStaticText();
  const valueOrId = value ?? id;
  const store = useFeatureStore();
  const index = useContext(TabIndexContext);
  const selectedTab = store?.useSelectedTab();
  
  const hostElemRef = useRef<HTMLButtonElement>(null);
  const indicatorElemRef = useRef<HTMLDivElement>(null);

  const isSelected = selectedTab?.id === id;

  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'tab',
    props: { type, size, color, additional },
    extraHostElementClassConditions: [
      { if: !!className, classes: () => [className] },
      { if: isSelected, classes: (cn) => [cn.selected] },
      { if: !isSelected, classes: (cn) => [cn.unselected] },
      { if: disabled, classes: (cn) => [cn.disabled] },
    ],
  });

  useLayoutEffect(() => {
    const headerTemp = typeof header === 'string' ? header : header(isSelected);
    const onClick = () => {
      if (!disabled) {
        store?.selectTabById(id);
      }
    };

    const tabTmp = (
      <button
        ref={hostElemRef}
        key={id}
        className={hostClassNames}
        onClick={onClick}>
        <div style={{ visibility: isSelected ? 'visible' : 'hidden'}} ref={indicatorElemRef} className={classNames.indicator} />
        <div className={classNames.headerWrapper}>
          {headerTemp}
        </div>
      </button>
    );

    const contentTmp = <div className={classNames.content} style={style}>{children}</div>;

    store?.registerTab({
      id,
      index,
      disabled,
      tabTmp,
      contentTmp,
      hostElemRef,
      indicatorElemRef,
      value: valueOrId,
    });
  }, [children, header, valueOrId, index, isSelected]);

  useOnDestroy(() => store?.unregisterTab(id));

  // This component does not render anything directly, it only registers itself in the store and the tabs component will render the tabTmp and contentTmp.
  return <></>;
};

Tab.displayName = 'Tab';
export default Tab;

// packages/angular/tabs/src/lib/tab/tab.component.ts
import { NgTemplateOutlet } from '@angular/common';
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  contentChild,
  ElementRef,
  inject,
  input,
  TemplateRef,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';

import { _UiBaseComponent } from '@cocokits/angular-core';

import { TabHeaderTemplateDirective } from './tab-header.tmpl-directive';
import { TabsFeatureStore } from '../tabs.feature-store';

let NEXT_ID = 1;

@Component({
  selector: 'cck-tab',
  imports: [NgTemplateOutlet],
  templateUrl: './tab.component.html',
  styleUrls: ['./tab.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  host: {
    '[class]': 'classNames().content',
  },
})
export class TabComponent<TValue = unknown> extends _UiBaseComponent<'tab'> {
  private featStore = inject(TabsFeatureStore);

  protected readonly componentName = 'tab';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.disabled(), classes: this.classNames().disabled },
    { if: this._isSelected(), classes: this.classNames().selected },
    { if: !this._isSelected(), classes: this.classNames().unselected },
  ]);

  public _id = `TAB_ID_${NEXT_ID++}`;

  /**
   * The label of the tab.
   */
  public header = input<string>();

  /**
   * The value of the tab, which is used to identify the tab when selected.
   * If not provided, a unique ID will be used.
   */
  public value = input<TValue>(undefined as TValue);

  public _value = computed(() => this.value() ?? this._id);

  /**
   * Whether the tab is disabled. If true, the tab will not be selectable by user.
   * @default false
   */
  public disabled = input(false, { transform: booleanAttribute });

  protected defaultHeaderTemplateContent = viewChild.required('defaultHeaderTemp', { read: TemplateRef });
  protected customHeaderTemplateContent = contentChild(TabHeaderTemplateDirective, { read: TemplateRef });
  protected headerTemplateContent = computed(
    () => this.customHeaderTemplateContent() ?? this.defaultHeaderTemplateContent()
  );
  public _headerTemplate = viewChild.required('headerTemp', { read: TemplateRef });

  public _contentTemplate = viewChild.required('contentTemp', { read: TemplateRef });

  public _isSelected = computed(() => this.featStore.selectedId() === this._id);

  public _indicatorElemRef = viewChild.required<unknown, ElementRef<HTMLElement>>('indicatorElemRef', {
    read: ElementRef<HTMLElement>,
  });

  protected toggle() {
    if (this.disabled()) {
      return;
    }
    this.featStore.selectTabById(this._id);
  }
}

<!-- Header Tab -->
<ng-template #headerTemp>
  
  <button [class]="hostClassNames()" (click)="toggle()">
    <div #indicatorElemRef [style.visibility]="_isSelected() ? 'visible' : 'hidden'" [class]="classNames().indicator"></div>

    <div [class]="classNames().headerWrapper">
      <ng-container *ngTemplateOutlet="headerTemplateContent(); context: { selected: _isSelected() }"></ng-container>
    </div>
  </button>
</ng-template>

<!-- Default Header Content -->
<ng-template #defaultHeaderTemp let-selected="selected">
  {{ header() }}
</ng-template>


<!-- Tab Content -->
<ng-template #contentTemp>
  <ng-content></ng-content>
</ng-template>
