// apps/angular-kits-doc/stories/ui-components/button/button/examples/stack-vertical-button/stack-vertical-button.component.ts
import { Component, input } from '@angular/core';

import { ButtonComponent, SvgIconComponent } from '@cocokits/angular-components';
import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/stack-vertical-button.config';

@Component({
  selector: 'cck-stack-vertical-button',
  imports: [ButtonComponent, SvgIconComponent],
  template: `
    <button
      cck-button
      [type]="cckExampleArgs().firstButtonType"
      [size]="cckExampleArgs().firstButtonSize"
      [color]="cckExampleArgs().firstButtonColor">
      Skip
    </button>

    <button
      cck-button
      [type]="cckExampleArgs().secondButtonType"
      [size]="cckExampleArgs().secondButtonSize"
      [color]="cckExampleArgs().secondButtonColor">
      Confirm
      <cck-svg-icon [icon]="Icons.arrowRight" />
    </button>
  `,
  styles: `
    :host {
      display: flex;
      flex-direction: column;
      width: 150px;
      gap: 12px;
    }
  `,
})
export class StackVerticalButtonComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  public Icons = Icons;
}

// apps/react-kits-doc/stories/ui-components/button/button/examples/stack-vertical-button/StackVerticalButton.tsx
import React from 'react';
import styled from "styled-components"

import { Icons } from '@cocokits/common-icons';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/button/stack-vertical-button.config';
import { Button, SvgIcon } from '@cocokits/react-components';

export function StackVerticalButton(props: { cckExampleArgs: ExampleArgs }) {
  return (
    <HostStyles>
      <Button
        type={props.cckExampleArgs.firstButtonType}
        size={props.cckExampleArgs.firstButtonSize}
        color={props.cckExampleArgs.firstButtonColor}>
        Skip
      </Button>

      <Button
        type={props.cckExampleArgs.secondButtonType}
        size={props.cckExampleArgs.secondButtonSize}
        color={props.cckExampleArgs.secondButtonColor}>
        Confirm
        <SvgIcon icon={Icons.arrowRight} />
      </Button>
    </HostStyles>
  );
}

const HostStyles = styled.div`
  display: flex;
  flex-direction: column;
  width: 150px;
  gap: 12px;
`;
