// packages/react/form-field/src/lib/select.tsx
/* eslint-disable max-lines-per-function */
'use client';
import { ReactNode, useContext, useEffect, useRef, useState } from 'react';

import { ElementAnchorPoint, isNotNullish } from '@cocokits/common-utils';
import { UIBaseComponentProps } from '@cocokits/core';
import { ThemeConfigContext, useUiBaseComponentConfig } from '@cocokits/react-core';
import { SvgIcon } from '@cocokits/react-icon';
import { OverlayPortal, OverlayPortalManager, RenderedOverlay } from '@cocokits/react-overlay';
import { useEffectAfterMount, useStaticText } from '@cocokits/react-utils';

import { useFormStore } from './form-store';
import { useCreateSelectStore } from './select-store';

export interface SelectProps<T = unknown> extends UIBaseComponentProps {
  /**
   * Whether the form field is disabled.
   */
  disabled?: boolean;
  /**
   * Whether the field is required.
   */
  required?: boolean;
  /**
   * Whether the user should be allowed to select multiple options.
   */
  multiple?: boolean;
  /**
   * Whether the form field is invalid.
   */
  invalid?: boolean;
  /**
   * Value of the select control.
   */
  value?: T | T[];

  /**
   * Placeholder to be shown if no value has been selected.
   */
  placeholder?: string;

  /**
   * The max-height of options overlay when it's open. If set to `null` there is no max-height, and it takes the height of content
   */
  maxOptionsHeight?: number;

  /**
   * Displays the select component with a customized view for the selected item,
   * enabling more complex and visually rich representations instead of just plain text.
   * If no present, the default preview will be used, witch it join all selected items with a comma.
   */
  selectPreview?: (selected: T[]) => React.ReactNode;

  /**
   * Event emitted when the selected value has been changed by the user.
   */
  onChange?: (selected: T[]) => void;

  /**
   * Event emitted when the select panel has been toggled.
   */
  onOpenedChange?: (opened: boolean) => void;

  /**
   * TODO: ...
   */
  anchorPoint?: ElementAnchorPoint;

  // TODO: Add this prop to the angular component too.
  /**
   * If true, the `onChange` event will only be emitted when the selected value has been changed.
   * Set it to `false` for scenarios where re-selection of the selected value should trigger a change event.
   * @default true
   */
  onlyEmitOnValueChange?: boolean;

  /**
   * The content inside the component.
   * This can be a string, a number, an element, or an array of elements.
   * It allows rendering nested components within this component.
   */
  children?: ReactNode | ReactNode[];
}

export const Select = <T,>(props: SelectProps<T>) => {
  const overlayId = useStaticText();
  const themeConfig = useContext(ThemeConfigContext);
  const dropdownIcon = themeConfig?.components.select?.templates?.dropdownIcon;

  if (!dropdownIcon) {
    throw new Error('`dropdownIcon` has not defined in `ThemeConfigToken` of selected theme');
  }

  const formStore = useFormStore();
  const { selectStore, SelectStoreProvider } = useCreateSelectStore({
    multiple: props.multiple,
    onSelectionChange: props.onChange,
    onlyEmitOnValueChange: props.onlyEmitOnValueChange,
  });
  const [isOpened, setIsOpened] = useState(false);
  const isEmpty = selectStore.useState((state) => state.isEmpty);
  const selectedItems = selectStore.useState((state) => state.selectedItems ?? []);
  const isMultiple = selectStore.useState((state) => state.isMultiple);

  const disabled = formStore?.useState((state) => state.disabled);
  const size = formStore?.useState((state) => state.size);

  const hostRef = useRef<HTMLDivElement>(null);

  let renderedOverlay: RenderedOverlay<unknown>;

  const { classNames, hostClassNames } = useUiBaseComponentConfig({
    componentName: 'select',
    props: { ...props, size },
    extraHostElementClassConditions: [
      { if: disabled, classes: (cn) => [cn.disabled] },
      { if: isMultiple, classes: (cn) => [cn.multiple] },
      { if: !isMultiple, classes: (cn) => [cn.single] },
      { if: isOpened, classes: (cn) => [cn.opened] },
      { if: !isOpened, classes: (cn) => [cn.closed] },
    ],
  });

  useEffectAfterMount(() => {
    selectStore.resetWithOption({ multiple: props.multiple });
  }, [props.multiple]);

  useEffect(() => {
    if (isNotNullish(props.value)) {
      selectStore.select(props.value, true);
    }
  }, [props.value]);

  useEffect(() => {
    formStore?.updateComponent('select', {
      disabled: props.disabled,
      required: props.required,
      invalid: props.invalid,
      size: props.size,
    });
    return () => {
      formStore?.unregisterComponent('select');
    };
  }, [formStore, props.disabled, props.required, props.invalid, props.size]);

  const onHostClick = async () => {
    // Don't do anything if there is an open overlay
    if (isOpened) {
      return;
    }

    setIsOpened(true);
    props.onOpenedChange?.(true);

    const connectTo = formStore?.components.formField?.wrapperElem ?? hostRef.current;

    if (!connectTo) {
      throw new Error('No wrapper element found for select component');
    }

    renderedOverlay = OverlayPortalManager.getWithId(overlayId).open({
      panelClass: [classNames.overlay],
      size: {
        minWidth: connectTo.getBoundingClientRect().width + 'px',
        maxHeight: props.maxOptionsHeight ? props.maxOptionsHeight + 'px' : '',
      },
      positionStrategy: {
        type: 'connectToElement',
        connectTo,
        anchorPoint: props.anchorPoint ?? ElementAnchorPoint.BottomLeft,
      },
    });

    await renderedOverlay.afterClosed;
    setIsOpened(false);
    props.onOpenedChange?.(false);
  };

  return (
    <SelectStoreProvider value={selectStore}>
      <div className={hostClassNames} onClick={onHostClick} ref={hostRef}>
        <div className={classNames.triggerWrapper}>
          {/* Trigger Content */}
          <div className={classNames.triggerValue}>
            {isEmpty ? (
              <div className={classNames.placeholder}>{props.placeholder}</div>
            ) : (
              (props.selectPreview?.(selectedItems) ?? selectedItems?.join(', '))
            )}
          </div>
        </div>

        <div className={classNames.dropdownIconWrapper}>
          <SvgIcon icon={dropdownIcon} />
        </div>

        {/* Overlay Wrapper */}
      </div>

      <OverlayPortal portalId={overlayId}>
        <div className={classNames.optionsWrapper}>{props.children}</div>
      </OverlayPortal>
    </SelectStoreProvider>
  );
};

Select.displayName = 'Select';

export default Select;

// packages/angular/form-field/src/lib/select/select.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  computed,
  contentChild,
  ElementRef,
  forwardRef,
  inject,
  Injector,
  Input,
  input,
  InputSignal,
  OnDestroy,
  OnInit,
  output,
  OutputEmitterRef,
  signal,
  TemplateRef,
  viewChild,
  ViewEncapsulation,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ControlValueAccessor, NG_VALUE_ACCESSOR, NgControl } from '@angular/forms';

import { _UiBaseComponent } from '@cocokits/angular-core';
import { SvgIconComponent } from '@cocokits/angular-icon';
import { OverlayConnectElemOrigin, OverlayService } from '@cocokits/angular-overlay';
import { isNullish, toBooleanOrPresent } from '@cocokits/common-utils';
import { ThemeSvgIcon } from '@cocokits/core';

import { injectFormFieldStore } from '../form-field.store';
import { injectSelectStore, SelectStore, SelectStoreService, SelectTriggerSource } from '../select.store';
import { SelectPreviewComponent } from '../select-preview/select-preview.component';
import { firstValueFrom } from 'rxjs';

const SELECT_CONTROL_VALUE_ACCESSOR: any = {
  provide: NG_VALUE_ACCESSOR,
  useExisting: forwardRef(() => SelectComponent),
  multi: true,
};

@Component({
  standalone: true,
  imports: [SvgIconComponent],
  selector: 'cck-select',
  templateUrl: './select.component.html',
  styleUrls: ['./select.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    SELECT_CONTROL_VALUE_ACCESSOR,
    {
      provide: SelectStore,
      useClass: SelectStoreService,
    },
  ],
  host: {
    '[class]': 'hostClassNames()',
    '(click)': 'onHostClick($event)',
  },
})
export class SelectComponent<T = any>
  extends _UiBaseComponent<'select'>
  implements OnInit, OnDestroy, ControlValueAccessor
{
  protected readonly componentName = 'select';
  protected extraHostElementClassConditions = computed(() => [
    { if: this.formFieldStore.state.disabled(), classes: this.classNames().disabled },
    { if: this.selectStore.isMultiple(), classes: this.classNames().multiple },
    { if: !this.selectStore.isMultiple(), classes: this.classNames().single },
    { if: this.isOpened(), classes: this.classNames().opened },
    { if: !this.isOpened(), classes: this.classNames().closed },
  ]);

  /** @ignore */
  override size = computed(() => this._size() ?? this.formFieldStore.formField.size?.());

  protected formFieldStore = injectFormFieldStore();
  protected selectStore = injectSelectStore<T>();
  private cd = inject(ChangeDetectorRef);
  private elemRef = inject<ElementRef<HTMLElement>>(ElementRef);
  private overlay = inject(OverlayService);
  private injector = inject(Injector);

  protected dropdownIcon: ThemeSvgIcon;
  private ngControl: NgControl | null = null;

  protected customTrigger = contentChild(SelectPreviewComponent);

  protected optionsTemp = viewChild('optionsTemp', { read: TemplateRef });

  protected triggerValue = computed(() => this.selectStore.selectedItems().join(', '));

  /**
   * Avoid using `effect` to listen for changes in selection and update the form controller value.
   * The `ControlValueAccessor` integrates with signals through the `formControl` function, which converts a form controller into a signal.
   * If we use effect, then we update another signal value inside the effect process, which is against Angular's signal guidelines.
   * The effect will listen to selectedItems from selectStore, and then update the form control value.
   * Following this, `formControl` will update all signals such as `value`, `touched` etc.
   *
   * From Angular Guidelines: When not to use effects
   * Avoid using effects for propagation of state changes.
   * This can result in ExpressionChangedAfterItHasBeenChecked errors,
   * infinite circular updates, or unnecessary change detection cycles.
   */
  private __onSelectedItemsChangedFromOption = this.selectStore.changes$
    .pipe(takeUntilDestroyed())
    .subscribe(({ selected, triggerSource }) => {
      if (triggerSource === SelectTriggerSource.FromOption) {
        this._controlValueAccessorChangeFn(selected);
        this._onTouched();
        this.selectionChange.emit(selected);
      }
    });

  /**
   * Whether the overlay to select an options is opened.
   * @storybook argType will be overridden by storybook
   */
  public isOpened = signal(false);
  // region ---------------- INPUTS ----------------

  /**
   * Whether the input is disabled.
   * @storybook argType will be overridden by storybook
   */
  public disabled = input(undefined, { transform: toBooleanOrPresent });

  /**
   * Whether the component is required.
   * @storybook argType will be overridden by storybook
   */
  public _required = input(undefined, { transform: toBooleanOrPresent, alias: 'required' });

  /**
   * Whether the user should be allowed to select multiple options.
   */
  @Input() set multiple(multiple: boolean) {
    this.selectStore.resetWithOption({ multiple });
  }

  /**
   * The max-height of options overlay when it's open. If set to `null` there is no max-height, and it takes the height of content
   */
  public maxOptionsHeight: InputSignal<number> = input<number>(220);

  /**
   * Value of the select control.
   */
  @Input() set value(value: T) {
    this.selectStore.setSelection(value);
  }

  /**
   * Placeholder to be shown if no value has been selected.
   */
  public placeholder: InputSignal<string> = input('');

  // endregion
  // region ---------------- OUTPUTS ----------------

  /**
   * Event emitted when the select panel has been toggled.
   */
  public openedChange: OutputEmitterRef<boolean> = output<boolean>();

  /**
   * Event emitted when the selected value has been changed by the user.
   */
  public selectionChange: OutputEmitterRef<T[]> = output<T[]>();

  // endregion

  constructor() {
    super();

    const dropdownIcon = this.themeConfig.components.select.templates?.dropdownIcon;

    if (!dropdownIcon) {
      throw new Error('`dropdownIcon` has not defined in `ThemeConfigToken` of selected theme');
    }
    this.dropdownIcon = dropdownIcon;

    this.formFieldStore.registerComponent('select', this, this.cd);
  }

  ngOnInit() {
    this.ngControl = this.injector.get<NgControl | null>(NgControl, null);

    if (this.ngControl?.control) {
      this.formFieldStore.setController(this.ngControl.control);
    }
  }

  protected async onHostClick(e: Event) {
    e.stopPropagation();

    if (this.formFieldStore.state.disabled()) {
      return;
    }

    const optionsTemp = this.optionsTemp();
    if (!optionsTemp) {
      throw new Error(`No options available for select component`);
    }

    const connectTo = this.formFieldStore.formField.wrapperElem?.()?.nativeElement ?? this.elemRef.nativeElement;

    this.selectStore.renderedOverlay = this.overlay.open<void, T>(optionsTemp, {
      panelClass: [this.classNames().overlay],
      size: {
        minWidth: connectTo.getBoundingClientRect().width + 'px',
        maxHeight: this.maxOptionsHeight() ? this.maxOptionsHeight() + 'px' : '',
      },
      positionStrategy: {
        type: 'connectToElement',
        connectTo,
        origin: OverlayConnectElemOrigin.BottomLeft,
      },
    });

    this.isOpened.set(true);
    this.openedChange.emit(true);
    this._onTouched();
    // await this.selectStore.renderedOverlay.afterClose;
    await firstValueFrom(this.selectStore.renderedOverlay.overlayRef.close$);
    this.openedChange.emit(false);
    this.isOpened.set(false);
  }

  ngOnDestroy() {
    this.formFieldStore.unregisterComponent(this, this.cd);
  }

  // region ---------------- ControlValueAccessor ----------------
  /**
   * Called when the select is blurred. Needed to properly implement ControlValueAccessor.
   * @docs-private
   */
  protected _onTouched: () => any = () => {
    // Do nothing.
  };

  private _controlValueAccessorChangeFn: (value: any) => void = () => {
    // Do nothing.
  };

  /**
   * Implemented as part of ControlValueAccessor.
   * @internal
   */
  writeValue(value: T | T[] | null | undefined) {
    isNullish(value)
      ? this.selectStore.clear({ triggerSource: SelectTriggerSource.FromControl })
      : this.selectStore.setSelection(value, { triggerSource: SelectTriggerSource.FromControl });
  }

  /**
   * Implemented as part of ControlValueAccessor.
   * @internal
   */
  registerOnChange(fn: (value: any) => void) {
    this._controlValueAccessorChangeFn = fn;
  }

  /**
   * Implemented as part of ControlValueAccessor.
   * @internal
   */
  registerOnTouched(fn: any) {
    this._onTouched = fn;
  }

  /**
   * Implemented as part of ControlValueAccessor.
   * @internal
   */
  setDisabledState(_isDisabled: boolean) {
    // Do nothing.
  }
  // endregion
}


<div [class]="classNames().triggerWrapper">

  @if(selectStore.isEmpty()) {
    <div [class]="classNames().placeholder">{{placeholder()}}</div>

  } @else {
    <div [class]="classNames().triggerValue">

      @if(customTrigger()) {
        <ng-content select="cck-select-preview"></ng-content>
      } @else {
        {{triggerValue()}}
      }
    </div>
  }

</div>

<div [class]="classNames().dropdownIconWrapper">
  <cck-svg-icon [icon]="dropdownIcon"></cck-svg-icon>
</div>

<ng-template #optionsTemp>
  <div [class]="classNames().optionsWrapper">
    <ng-content></ng-content>
  </div>
</ng-template>
