// apps/react-kits-doc/stories/ui-components/form-field/form-field/examples/trailing-select-amount/TrailingSelectAmount.tsx
import { useState } from 'react';

import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/trailing-select-amount.config';
import { FormField, Input, Label, Option, Select, Trailing } from '@cocokits/react-components';

import { formatValue, unFormatValue } from './TrailingSelectAmount.util';

export function TrailingSelectAmount(props: { cckExampleArgs: ExampleArgs }) {

  const [value, setValue] = useState('');

  return (
    <FormField>
      <Label>Select amount</Label>
      <Input
        value={value}
        onFocus={() => setValue(unFormatValue(value))}
        onBlur={() => setValue(formatValue(value))}
        onChange={e => setValue(e.target.value)}/>
      <Trailing>
        <Select value="USD">
          <Option value="USD">USD</Option>
          <Option value="EUR">EUR</Option>
          <Option value="JPY">JPY</Option>
          <Option value="CNY">CNY</Option>
          <Option value="KRW">KRW</Option>
        </Select>
      </Trailing>
    </FormField>
  );
}

// apps/angular-kits-doc/stories/ui-components/form-field/form-field/examples/trailing-select-amount/trailing-select-amount.component.ts
import { Component, input, signal } from '@angular/core';

import {
  FormFieldComponent,
  InputComponent,
  LabelComponent,
  OptionComponent,
  SelectComponent,
  TrailingComponent,
} from '@cocokits/angular-components';
import { ExampleArgs } from '@cocokits/common-kits-doc/examples-config/form-field/trailing-select-amount.config';

import { formatValue, unFormatValue } from './trailing-select-amount.util';

@Component({
  standalone: true,
  selector: 'cck-trailing-select-amount',
  imports: [FormFieldComponent, InputComponent, TrailingComponent, LabelComponent, SelectComponent, OptionComponent],
  template: `
    <cck-form-field>
      <cck-label>Select amount</cck-label>
      <input cck-input (change)="onChange($event)" (focus)="onFocus()" (blur)="onBlur()" [value]="value()" />
      <cck-trailing>
        <cck-select value="USD">
          <cck-option value="USD">USD</cck-option>
          <cck-option value="EUR">EUR</cck-option>
          <cck-option value="JPY">JPY</cck-option>
          <cck-option value="CNY">CNY</cck-option>
          <cck-option value="KRW">KRW</cck-option>
        </cck-select>
      </cck-trailing>
    </cck-form-field>
  `,
  styles: ``,
})
export class TrailingSelectAmountComponent {
  public cckExampleArgs = input.required<ExampleArgs>();
  protected value = signal('');

  protected onChange(event: Event) {
    this.value.set((event.currentTarget as HTMLInputElement).value);
  }

  protected onFocus() {
    this.value.set(unFormatValue(this.value()));
  }

  protected onBlur() {
    this.value.set(formatValue(this.value()));
  }
}
